/** First-run workspace: the client's Aura Villa plus three generated projects at different stages. */
import type { ProjectDoc, StyleId, WorkflowStage } from '../core/model/types';
import { auraVilla } from '../core/generate/auraVilla';
import { defaultMeta, newProjectDoc } from '../core/model/factory';
import { DEFAULT_PROGRAM, generateSchemes, siteFromProgram, type Program, type Strategy } from '../core/generate/layout';
import { ft } from '../core/units';
import { uid } from '../core/model/ids';
import { CITIES } from '../core/derive/sun';

export interface Template { id: string; name: string; description: string; tags: string[]; build: () => ProjectDoc }

function generated(opts: {
  name: string; city: string; w: number; d: number; program: Partial<Program>; strategy: Strategy; stage: WorkflowStage; phase: string;
  ownerId?: string; ageDays: number; client: string; type?: ProjectDoc['meta']['type'];
}): ProjectDoc {
  const site = siteFromProgram(ft(opts.w), ft(opts.d));
  const program: Program = { ...DEFAULT_PROGRAM, ...opts.program };
  const scheme = generateSchemes(site, program, [opts.strategy])[0];
  const loc = CITIES.find((c) => c.city === opts.city) ?? CITIES[0];
  const meta = defaultMeta({
    name: opts.name, client: opts.client, phase: opts.phase, type: opts.type ?? 'villa', tags: [`${program.bedrooms} BHK`, program.floors > 1 ? `G+${program.floors - 1}` : 'Single storey'],
    location: { city: loc.city, country: loc.country, lat: loc.lat, lon: loc.lon },
    ownerId: opts.ownerId ?? 'u-ronak',
  });
  if (opts.ownerId) meta.members = [{ userId: opts.ownerId, role: 'owner' }, { userId: 'u-ronak', role: 'architect' }, { userId: 'u-priya', role: 'designer' }];
  const doc = newProjectDoc(meta, site, scheme.building, scheme.style as StyleId);
  doc.options[0].name = scheme.name;
  doc.options[0].description = scheme.summary;
  for (const f of scheme.features) doc.site.features[f.id] = f;
  doc.site.northAngle = scheme.northAngle;
  doc.stage = opts.stage;
  const now = Date.now();
  doc.meta.createdAt = now - opts.ageDays * 86400e3;
  doc.meta.updatedAt = now - (opts.ageDays / 6) * 86400e3;
  doc.activity = [{ id: uid('act'), at: doc.meta.updatedAt, actorId: opts.ownerId ?? 'u-ronak', action: 'layout.generate', summary: `${scheme.name} generated by Architect AI` }];
  return doc;
}

export function seedProjects(): ProjectDoc[] {
  return [
    auraVilla(),
    generated({ name: 'Modern Villa', city: 'Goa', w: 40, d: 60, program: { bedrooms: 4, floors: 2, pool: false }, strategy: 'compact', stage: 'internal_review', phase: 'Concept design', ageDays: 9, client: 'D’Souza family' }),
    generated({ name: 'Courtyard House', city: 'Pune', w: 60, d: 90, program: { bedrooms: 3, floors: 2, pool: true, study: true }, strategy: 'courtyard', stage: 'draft', phase: 'Schematic design', ageDays: 3, client: 'Kulkarni residence' }),
    generated({ name: 'Hillside Farmhouse', city: 'Pune', w: 80, d: 100, program: { bedrooms: 3, floors: 1, pool: true, style: 'traditional' }, strategy: 'linear', stage: 'approved', phase: 'Design development', ownerId: 'u-meera', ageDays: 40, client: 'Mehra estate', type: 'farmhouse' }),
  ];
}

export const TEMPLATES: Template[] = [
  { id: 'aura', name: 'Aura Villa — L-plot G+1', description: '5 BHK modern villa on a 4,522 sq ft L-shaped plot with pool, from a real client sketch.', tags: ['Villa', 'G+1', 'Pool'], build: () => auraVilla() },
  { id: 'duplex-30x40', name: 'Compact duplex 30 × 40', description: '3 BHK duplex for a standard 1,200 sq ft plot.', tags: ['Duplex', '3 BHK'], build: () => generated({ name: 'Compact Duplex', city: 'Bengaluru', w: 30, d: 40, program: { bedrooms: 3, floors: 2, pooja: true, powder: false, family: false, parking: 1, garden: false }, strategy: 'compact', stage: 'draft', phase: 'Concept design', ageDays: 0, client: 'New client', type: 'duplex' }) },
  { id: 'villa-40x60', name: 'Villa 40 × 60', description: '4 BHK G+1 villa with family lounge and pooja room.', tags: ['Villa', '4 BHK'], build: () => generated({ name: 'Villa 40 × 60', city: 'Hyderabad', w: 40, d: 60, program: { bedrooms: 4, floors: 2 }, strategy: 'compact', stage: 'draft', phase: 'Concept design', ageDays: 0, client: 'New client' }) },
  { id: 'luxury-60x100', name: 'Luxury courtyard villa 60 × 100', description: '5 BHK courtyard villa with pool and study.', tags: ['Luxury', 'Courtyard', 'Pool'], build: () => generated({ name: 'Courtyard Villa', city: 'Alibaug', w: 60, d: 100, program: { bedrooms: 5, floors: 2, pool: true, study: true, style: 'luxury' }, strategy: 'courtyard', stage: 'draft', phase: 'Concept design', ageDays: 0, client: 'New client' }) },
  { id: 'bungalow', name: 'Single-storey bungalow', description: '3 BHK bungalow with deep tropical overhangs.', tags: ['Bungalow', 'Tropical'], build: () => generated({ name: 'Garden Bungalow', city: 'Chennai', w: 50, d: 80, program: { bedrooms: 3, floors: 1, style: 'tropical' }, strategy: 'linear', stage: 'draft', phase: 'Concept design', ageDays: 0, client: 'New client', type: 'bungalow' }) },
];
