/**
 * Ready-made space blocks — standard rooms, suites, cores, outdoor spaces and
 * whole home kits that anyone can drag onto a plan. Blocks are *data*: placing
 * one runs normal model operations (walls only where missing, doors, windows,
 * furniture), so a dropped block is as editable as anything drawn by hand.
 *
 * Dimensions are wall centre-lines in feet (converted on placement) and sized
 * to pass the bundled residential room standards.
 */
import type { RoomFunction, SiteFeatureKind, DoorKind } from '../model/types';

export type Side = 'n' | 's' | 'e' | 'w';
export type BlockCategory = 'kits' | 'bedrooms' | 'bathrooms' | 'kitchens' | 'living' | 'work' | 'utility' | 'circulation' | 'parking' | 'outdoor' | 'garden';

export interface ItemSpec { asset: string; side: Side | 'center'; along?: number; gap?: number; rot?: number }

export interface BlockPart {
  key: string;
  name: string;
  fn: RoomFunction;
  x: number; y: number; w: number; h: number;
  /** Edges that are open (parapet / railing height) instead of full walls. */
  open?: Side[];
  stair?: 'U' | 'straight' | 'L';
  /** Explicit furniture; when absent the room is furnished automatically from its function. */
  items?: ItemSpec[];
  furnish?: boolean;
}

export interface BlockDoor { a: string; b: string | Side; kind?: DoorKind; width?: number }
export interface BlockSite { kind: SiteFeatureKind; name: string; x: number; y: number; w: number; h: number; material: string; cars?: number }
export interface BlockProp { asset: string; x: number; y: number; rot?: number; variant?: string }

export interface BlockSize {
  id: 'S' | 'M' | 'L';
  label: string;
  /** Footprint in feet (for kits: the plot the kit is designed for). */
  w: number;
  d: number;
  fits: string;
  parts: BlockPart[];
  doors?: BlockDoor[];
  site?: BlockSite[];
  props?: BlockProp[];
}

export interface BlockDef {
  id: string;
  name: string;
  category: BlockCategory;
  description: string;
  /** Part that connects to the neighbouring room when dropped (default: first part). */
  entry?: string;
  /** Door used to connect to the neighbour. */
  entryDoor?: DoorKind;
  /** Site-only blocks (pools, parking, lawns) — placed on the ground level, outside the building. */
  siteOnly?: boolean;
  /** Whole-home kits are generated by the layout engine for the given plot. */
  kit?: { bedrooms: number; pooja?: boolean; study?: boolean; powder?: boolean };
  sizes: BlockSize[];
  keywords: string[];
}

export const BLOCK_CATEGORIES: { id: BlockCategory; label: string; hint: string }[] = [
  { id: 'kits', label: 'Home kits', hint: 'Complete homes — drop one and start editing' },
  { id: 'bedrooms', label: 'Bedrooms', hint: 'Rooms and suites with beds, wardrobes and baths' },
  { id: 'bathrooms', label: 'Bathrooms', hint: 'Powder rooms to luxury baths' },
  { id: 'kitchens', label: 'Kitchens', hint: 'Straight, L, U, parallel and island' },
  { id: 'living', label: 'Living & dining', hint: 'Living, dining, family and theatre' },
  { id: 'work', label: 'Work & wellness', hint: 'Office, gym, yoga and pooja' },
  { id: 'utility', label: 'Utility & storage', hint: 'Laundry, store and walk-in' },
  { id: 'circulation', label: 'Entry, stairs & lift', hint: 'Foyer, corridors, stairs and lift cores' },
  { id: 'parking', label: 'Parking', hint: 'Standard car bays (2.5 × 5 m), garages, two-wheelers' },
  { id: 'outdoor', label: 'Outdoor living', hint: 'Patios, sit-outs, pergolas, fire pits, pools and play' },
  { id: 'garden', label: 'Gardens', hint: 'Ready-planted lawns, borders, courts and screens' },
];

const P = (key: string, name: string, fn: RoomFunction, x: number, y: number, w: number, h: number, extra: Partial<BlockPart> = {}): BlockPart => ({ key, name, fn, x, y, w, h, ...extra });
const one = (name: string, fn: RoomFunction, w: number, d: number, extra: Partial<BlockPart> = {}) => [P('room', name, fn, 0, 0, w, d, extra)];

const LUX_BATH: ItemSpec[] = [{ asset: 'vanity', side: 's', along: 0.15 }, { asset: 'wc', side: 's', along: 0.85 }, { asset: 'bathtub', side: 'n', along: 0.35 }, { asset: 'shower', side: 'e', along: 0.95 }];

type FrontCol = [string, string, RoomFunction, number] | [string, string, RoomFunction, number, number, string, string, RoomFunction];

/**
 * Whole-home kit on the classic residential diagram: a public band at the
 * front (living, dining, kitchen …), a spine corridor, and bedroom suites
 * (bedroom + bath + dressing) at the back. Every room meets the room standards.
 */
function homeKit(W: number, frontD: number, front: FrontCol[], spine: number, suites: number, suiteW: number, bedD: number, bathD: number): Pick<BlockSize, 'parts' | 'doors'> {
  const parts: BlockPart[] = [];
  const doors: BlockDoor[] = [{ a: 'liv', b: 's', kind: 'pivot', width: 1200 }];
  let x = 0;
  for (const col of front) {
    const [key, name, fn, w] = col;
    // The last column takes whatever width remains, so the band always tiles exactly.
    const width = col === front[front.length - 1] ? W - x : w;
    if (col.length === 8) {
      const [, , , , h1, key2, name2, fn2] = col;
      parts.push(P(key, name, fn, x, 0, width, h1), P(key2, name2, fn2, x, h1, width, frontD - h1));
    } else parts.push(P(key, name, fn, x, 0, width, frontD));
    x += width;
  }
  parts.push(P('spine', 'Passage', 'corridor', 0, frontD, W, spine));
  const y0 = frontD + spine;
  const half = suiteW / 2;
  for (let i = 0; i < suites; i++) {
    const sx = i * suiteW;
    const sw = i === suites - 1 ? W - sx : suiteW;
    const master = i === 0;
    const bed = master ? 'Master Bedroom' : `Bedroom ${i + 1}`;
    parts.push(P(`bed${i}`, bed, master ? 'master_bedroom' : 'bedroom', sx, y0, sw, bedD));
    parts.push(P(`bath${i}`, master ? 'Master Bath' : `Bath ${i + 1}`, 'bathroom', sx, y0 + bedD, half, bathD));
    parts.push(P(`dr${i}`, master ? 'Walk-in Wardrobe' : `Dressing ${i + 1}`, 'walkin', sx + half, y0 + bedD, sw - half, bathD));
    doors.push({ a: `bed${i}`, b: 'spine' }, { a: `bath${i}`, b: `bed${i}` }, { a: `dr${i}`, b: `bed${i}`, kind: 'opening', width: 800 });
  }
  const keys = new Set(parts.map((p) => p.key));
  doors.push({ a: 'spine', b: 'liv', kind: 'opening', width: 1100 });
  if (keys.has('din')) doors.push({ a: 'din', b: 'liv', kind: 'opening', width: 1800 });
  if (keys.has('kit')) doors.push({ a: 'kit', b: 'din' });
  if (keys.has('ut')) doors.push({ a: 'ut', b: 'kit' });
  if (keys.has('st')) doors.push({ a: 'st', b: 'kit', kind: 'opening', width: 900 });
  if (keys.has('pj')) doors.push({ a: 'pj', b: 'liv' });
  if (keys.has('pw')) doors.push({ a: 'pw', b: 'spine' });
  return { parts, doors };
}

/**
 * Narrow-plot kit: living across the front, dining + kitchen, then a central
 * passage with a bedroom + bath on each side (every bedroom keeps an outside
 * wall for daylight) and, optionally, a full-width master suite at the back.
 */
function narrowKit(W: number, livD: number, dinW: number, midD: number, colW: number, bedD: number, bathD: number, master?: { bedD: number; bathD: number }): Pick<BlockSize, 'parts' | 'doors'> {
  const parts: BlockPart[] = [P('liv', 'Living Room', 'living', 0, 0, W, livD), P('din', 'Dining', 'dining', 0, livD, dinW, midD), P('kit', 'Kitchen', 'kitchen', dinW, livD, W - dinW, midD)];
  const y0 = livD + midD;
  const depth = bedD + bathD;
  parts.push(P('spine', 'Passage', 'corridor', colW, y0, W - 2 * colW, depth));
  const doors: BlockDoor[] = [{ a: 'liv', b: 's', kind: 'pivot', width: 1200 }, { a: 'din', b: 'liv', kind: 'opening', width: 1800 }, { a: 'kit', b: 'din' }, { a: 'spine', b: 'din', kind: 'opening', width: 1000 }];
  [0, W - colW].forEach((x, i) => {
    parts.push(P(`bed${i}`, `Bedroom ${i + 1}`, 'bedroom', x, y0, colW, bedD), P(`bath${i}`, `Bath ${i + 1}`, 'bathroom', x, y0 + bedD, colW, bathD));
    doors.push({ a: `bed${i}`, b: 'spine' }, { a: `bath${i}`, b: `bed${i}` });
  });
  if (master) {
    const ym = y0 + depth;
    parts.push(P('mbed', 'Master Bedroom', 'master_bedroom', 0, ym, W, master.bedD), P('mbath', 'Master Bath', 'bathroom', 0, ym + master.bedD, W / 2, master.bathD), P('mwi', 'Walk-in Wardrobe', 'walkin', W / 2, ym + master.bedD, W / 2, master.bathD));
    doors.push({ a: 'mbed', b: 'spine' }, { a: 'mbath', b: 'mbed' }, { a: 'mwi', b: 'mbed', kind: 'opening', width: 800 });
  }
  return { parts, doors };
}

/** A plant from the nursery catalogue, as a placeable asset id. */
const PL = (plantId: string) => `plant-${plantId}`;

export const BLOCKS: BlockDef[] = [
  // ------------------------------------------------------------- home kits
  { id: 'kit-1bhk', name: '1 BHK home', category: 'kits', keywords: ['1bhk', 'one bedroom', 'starter', 'small home', 'apartment'], description: 'Living, dining, kitchen, utility and a bedroom with attached bath — a complete small home.',
    sizes: [
      { id: 'S', label: 'Compact', w: 24, d: 28, fits: 'About 670 sq ft', parts: [P('liv', 'Living Room', 'living', 0, 0, 14, 13), P('din', 'Dining', 'dining', 14, 0, 10, 13), P('bed', 'Bedroom', 'bedroom', 0, 13, 14, 15), P('kit', 'Kitchen', 'kitchen', 14, 13, 10, 9), P('bath', 'Bath', 'bathroom', 14, 22, 6, 6), P('ut', 'Utility', 'utility', 20, 22, 4, 6)],
        doors: [{ a: 'liv', b: 's', kind: 'pivot', width: 1100 }, { a: 'din', b: 'liv', kind: 'opening', width: 1800 }, { a: 'kit', b: 'din' }, { a: 'bed', b: 'liv' }, { a: 'bath', b: 'bed' }, { a: 'ut', b: 'kit' }] },
      { id: 'M', label: 'Standard', w: 28, d: 30, fits: 'About 840 sq ft', parts: [P('liv', 'Living Room', 'living', 0, 0, 16, 14), P('din', 'Dining', 'dining', 16, 0, 12, 14), P('bed', 'Bedroom', 'bedroom', 0, 14, 15, 16), P('kit', 'Kitchen', 'kitchen', 15, 14, 13, 9), P('bath', 'Bath', 'bathroom', 15, 23, 7, 7), P('ut', 'Utility', 'utility', 22, 23, 6, 7)],
        doors: [{ a: 'liv', b: 's', kind: 'pivot', width: 1100 }, { a: 'din', b: 'liv', kind: 'opening', width: 2100 }, { a: 'kit', b: 'din' }, { a: 'bed', b: 'liv' }, { a: 'bath', b: 'bed' }, { a: 'ut', b: 'kit' }] },
    ] },
  { id: 'kit-2bhk', name: '2 BHK home', category: 'kits', keywords: ['2bhk', 'two bedroom', 'apartment', 'house'], description: 'Two bedroom suites off a central passage, with living, dining, kitchen and utility.',
    sizes: [
      { id: 'S', label: 'Compact', w: 32, d: 40, fits: 'About 1,280 sq ft', ...homeKit(32, 15, [['liv', 'Living Room', 'living', 16], ['din', 'Dining', 'dining', 9], ['kit', 'Kitchen', 'kitchen', 7, 10, 'ut', 'Utility', 'utility']], 4, 2, 16, 13, 8) },
      { id: 'M', label: 'Standard', w: 36, d: 42, fits: 'About 1,510 sq ft', ...homeKit(36, 16, [['liv', 'Living Room', 'living', 18], ['din', 'Dining', 'dining', 10], ['kit', 'Kitchen', 'kitchen', 8, 11, 'ut', 'Utility', 'utility']], 4, 2, 18, 14, 8) },
    ] },
  { id: 'kit-3bhk', name: '3 BHK home', category: 'kits', keywords: ['3bhk', 'three bedroom', 'family home', 'house'], description: 'Three bedroom suites, pooja and powder room, living, dining, kitchen and utility.',
    sizes: [
      { id: 'S', label: 'Compact', w: 42, d: 44, fits: 'About 1,850 sq ft', ...homeKit(42, 15, [['pj', 'Pooja', 'pooja', 6, 7, 'pw', 'Powder Room', 'powder'], ['liv', 'Living Room', 'living', 14], ['din', 'Dining', 'dining', 12], ['kit', 'Kitchen', 'kitchen', 10, 10, 'ut', 'Utility', 'utility']], 4, 3, 14, 15, 10) },
      { id: 'M', label: 'Spacious', w: 48, d: 46, fits: 'About 2,200 sq ft', ...homeKit(48, 16, [['pj', 'Pooja', 'pooja', 7, 8, 'pw', 'Powder Room', 'powder'], ['liv', 'Living Room', 'living', 17], ['din', 'Dining', 'dining', 12], ['kit', 'Kitchen', 'kitchen', 12, 11, 'ut', 'Utility', 'utility']], 4, 3, 16, 15, 11) },
    ] },
  { id: 'kit-2bhk-narrow', name: '2 BHK narrow-plot home', category: 'kits', keywords: ['2bhk', 'narrow plot', 'row house', '30x50', '30 x 60', 'two bedroom'], description: 'Built for narrow plots: living at the front, kitchen and dining in the middle, a bedroom with its own bath on each side of a central passage.',
    sizes: [
      { id: 'S', label: 'Compact', w: 24, d: 44, fits: 'About 1,050 sq ft · fits a 40 × 60 ft plot', ...narrowKit(24, 13, 14, 11, 10, 13, 7) },
      { id: 'M', label: 'Standard', w: 26, d: 48, fits: 'About 1,250 sq ft · fits a 35 × 65 ft plot', ...narrowKit(26, 14, 14, 11, 11, 15, 8) },
    ] },
  { id: 'kit-3bhk-narrow', name: '3 BHK narrow-plot home', category: 'kits', keywords: ['3bhk', 'narrow plot', 'row house', '30x60', '40x60', 'three bedroom'], description: 'Two bedroom suites off a central passage and a full-width master suite at the back — for 35–40 ft wide plots.',
    sizes: [{ id: 'S', label: 'Narrow', w: 26, d: 64, fits: 'About 1,660 sq ft · fits a 35 × 80 ft plot', ...narrowKit(26, 14, 14, 11, 11, 13, 7, { bedD: 13, bathD: 6 }) }] },
  { id: 'kit-4bhk', name: '4 BHK single-storey villa', category: 'kits', keywords: ['4bhk', 'villa', 'bungalow', 'four bedroom', 'single floor'], description: 'A single-floor villa with four suites, pooja, powder room, generous living, dining and kitchen.',
    sizes: [
      { id: 'M', label: 'Villa', w: 60, d: 45, fits: 'About 2,700 sq ft', ...homeKit(60, 16, [['pj', 'Pooja', 'pooja', 7, 8, 'pw', 'Powder Room', 'powder'], ['liv', 'Living Room', 'living', 21], ['din', 'Dining', 'dining', 14], ['kit', 'Kitchen', 'kitchen', 12, 11, 'st', 'Pantry & Store', 'store'], ['ut', 'Utility', 'utility', 6]], 4, 4, 15, 15, 10) },
    ] },

  // ------------------------------------------------------------- bedrooms
  { id: 'bedroom', name: 'Bedroom', category: 'bedrooms', keywords: ['bedroom', 'room', 'sleep'], description: 'A furnished bedroom with bed, side tables and wardrobe.',
    sizes: [
      { id: 'S', label: 'Cozy', w: 11, d: 11, fits: 'Double bed · wardrobe', parts: one('Bedroom', 'bedroom', 11, 11) },
      { id: 'M', label: 'Standard', w: 12, d: 12, fits: 'King bed · wardrobe · side tables', parts: one('Bedroom', 'bedroom', 12, 12) },
      { id: 'L', label: 'Spacious', w: 14, d: 14, fits: 'King bed · wardrobe · seating', parts: one('Bedroom', 'bedroom', 14, 14) },
    ] },
  { id: 'bedroom-bath', name: 'Bedroom + attached bath', category: 'bedrooms', keywords: ['bedroom', 'attached bathroom', 'ensuite', 'suite'], description: 'Bedroom with its own bathroom and a dressing nook.',
    sizes: [
      { id: 'S', label: 'Cozy', w: 16, d: 11, fits: 'Queen bed · bath · dressing', parts: [P('bed', 'Bedroom', 'bedroom', 0, 0, 11, 11), P('bath', 'Bath', 'bathroom', 11, 4, 5, 7), P('dress', 'Dressing', 'walkin', 11, 0, 5, 4)], doors: [{ a: 'bath', b: 'bed' }, { a: 'dress', b: 'bed', kind: 'opening', width: 800 }] },
      { id: 'M', label: 'Standard', w: 18, d: 12, fits: 'King bed · bath · dressing', parts: [P('bed', 'Bedroom', 'bedroom', 0, 0, 12, 12), P('bath', 'Bath', 'bathroom', 12, 4, 6, 8), P('dress', 'Dressing', 'walkin', 12, 0, 6, 4)], doors: [{ a: 'bath', b: 'bed' }, { a: 'dress', b: 'bed', kind: 'opening', width: 800 }] },
      { id: 'L', label: 'Spacious', w: 21, d: 14, fits: 'King bed · large bath · walk-in', parts: [P('bed', 'Bedroom', 'bedroom', 0, 0, 14, 14), P('bath', 'Bath', 'bathroom', 14, 5, 7, 9), P('dress', 'Walk-in', 'walkin', 14, 0, 7, 5)], doors: [{ a: 'bath', b: 'bed' }, { a: 'dress', b: 'bed' }] },
    ] },
  { id: 'master-suite', name: 'Master suite', category: 'bedrooms', keywords: ['master', 'master bedroom', 'suite', 'walk-in', 'primary'], description: 'Master bedroom with walk-in wardrobe and a full bathroom.',
    sizes: [
      { id: 'S', label: 'Standard', w: 21, d: 13, fits: 'King bed · walk-in · bath', parts: [P('bed', 'Master Bedroom', 'master_bedroom', 0, 0, 14, 13), P('wi', 'Walk-in Wardrobe', 'walkin', 14, 0, 7, 6), P('bath', 'Master Bath', 'bathroom', 14, 6, 7, 7)], doors: [{ a: 'wi', b: 'bed' }, { a: 'bath', b: 'bed' }] },
      { id: 'M', label: 'Generous', w: 24, d: 14, fits: 'King bed · lounge chair · large bath', parts: [P('bed', 'Master Bedroom', 'master_bedroom', 0, 0, 16, 14), P('wi', 'Walk-in Wardrobe', 'walkin', 16, 0, 8, 6), P('bath', 'Master Bath', 'bathroom', 16, 6, 8, 8)], doors: [{ a: 'wi', b: 'bed' }, { a: 'bath', b: 'bed' }] },
      { id: 'L', label: 'Luxury', w: 27, d: 16, fits: 'King bed · walk-in · bathtub & shower', parts: [P('bed', 'Master Bedroom', 'master_bedroom', 0, 0, 18, 16), P('wi', 'Walk-in Wardrobe', 'walkin', 18, 0, 9, 7), P('bath', 'Master Bath', 'bathroom', 18, 7, 9, 9, { items: LUX_BATH })], doors: [{ a: 'wi', b: 'bed' }, { a: 'bath', b: 'bed' }] },
    ] },
  { id: 'kids-room', name: "Kids' room with study", category: 'bedrooms', keywords: ['kids', 'children', 'child', 'study', 'bunk'], description: 'Bed, study desk, bookshelf and wardrobe for a growing child.',
    sizes: [
      { id: 'S', label: 'Bunk', w: 10.5, d: 12, fits: 'Bunk bed · desk · wardrobe', parts: one("Kids' Room", 'bedroom', 10.5, 12, { items: [{ asset: 'bunk-bed', side: 'w', along: 0.95 }, { asset: 'desk', side: 'n', along: 0.85 }, { asset: 'wardrobe', side: 'e', along: 0.1 }] }) },
      { id: 'M', label: 'Standard', w: 12, d: 13, fits: 'Single bed · desk · bookshelf', parts: one("Kids' Room", 'bedroom', 12, 13, { items: [{ asset: 'bed-single', side: 'w', along: 0.95 }, { asset: 'desk', side: 'n', along: 0.85 }, { asset: 'bookshelf', side: 'e', along: 0.6 }, { asset: 'wardrobe', side: 's', along: 0.85 }] }) },
    ] },
  { id: 'guest-suite', name: 'Guest suite', category: 'bedrooms', keywords: ['guest', 'guest room', 'parents', 'ground floor bedroom'], description: 'A self-contained guest bedroom with its own bath — ideal on the ground floor.',
    sizes: [
      { id: 'S', label: 'Standard', w: 17, d: 12, fits: 'Queen bed · bath', parts: [P('bed', 'Guest Bedroom', 'bedroom', 0, 0, 11.5, 12), P('bath', 'Guest Bath', 'bathroom', 11.5, 0, 5.5, 8), P('st', 'Guest Store', 'store', 11.5, 8, 5.5, 4)], doors: [{ a: 'bath', b: 'bed' }, { a: 'st', b: 'bed', kind: 'opening', width: 800 }] },
      { id: 'M', label: 'Generous', w: 19, d: 13, fits: 'King bed · bath · storage', parts: [P('bed', 'Guest Bedroom', 'bedroom', 0, 0, 13, 13), P('bath', 'Guest Bath', 'bathroom', 13, 0, 6, 8), P('st', 'Guest Store', 'store', 13, 8, 6, 5)], doors: [{ a: 'bath', b: 'bed' }, { a: 'st', b: 'bed', kind: 'opening', width: 800 }] },
    ] },
  { id: 'staff-room', name: 'Staff room + WC', category: 'bedrooms', keywords: ['staff', 'servant', 'maid', 'driver', 'help'], description: 'A compact room with its own toilet for household staff.',
    sizes: [{ id: 'S', label: 'Standard', w: 16, d: 11, fits: 'Single bed · WC · store', parts: [P('room', 'Staff Room', 'bedroom', 0, 0, 11, 11, { items: [{ asset: 'bed-single', side: 'w', along: 0.9 }, { asset: 'wardrobe', side: 's', along: 0.9 }] }), P('wc', 'Staff WC', 'bathroom', 11, 0, 5, 7), P('st', 'Staff Store', 'store', 11, 7, 5, 4)], doors: [{ a: 'wc', b: 'room' }, { a: 'st', b: 'room', kind: 'opening', width: 800 }] }] },

  // ------------------------------------------------------------- bathrooms
  { id: 'powder', name: 'Powder room', category: 'bathrooms', keywords: ['powder', 'guest toilet', 'wc', 'half bath'], description: 'Basin and WC for guests, near living spaces.',
    sizes: [{ id: 'S', label: 'Compact', w: 4, d: 5.5, fits: 'WC · basin', parts: one('Powder Room', 'powder', 4, 5.5) }, { id: 'M', label: 'Standard', w: 5, d: 6, fits: 'WC · vanity', parts: one('Powder Room', 'powder', 5, 6) }] },
  { id: 'bath', name: 'Bathroom', category: 'bathrooms', keywords: ['bathroom', 'toilet', 'washroom', 'shower', 'bath'], description: 'A full bathroom with WC, basin and shower.',
    sizes: [
      { id: 'S', label: 'Compact', w: 5, d: 7, fits: 'WC · basin · shower', parts: one('Bathroom', 'bathroom', 5, 7) },
      { id: 'M', label: 'Standard', w: 6, d: 8, fits: 'WC · vanity · walk-in shower', parts: one('Bathroom', 'bathroom', 6, 8) },
      { id: 'L', label: 'Luxury', w: 9, d: 10, fits: 'Bathtub · shower · vanity · WC', parts: one('Bathroom', 'bathroom', 9, 10, { items: LUX_BATH }) },
    ] },
  { id: 'common-bath', name: 'Shared bath (two doors)', category: 'bathrooms', keywords: ['jack and jill', 'shared bathroom', 'common toilet'], description: 'A bathroom with a wet and a dry zone, shared by two rooms.',
    sizes: [{ id: 'M', label: 'Standard', w: 6, d: 11, fits: 'Dry vanity zone · wet zone', parts: [P('dry', 'Dry Bath', 'bathroom', 0, 0, 6, 4.5, { items: [{ asset: 'vanity', side: 'w', along: 0.5 }] }), P('wet', 'Wet Bath', 'bathroom', 0, 4.5, 6, 6.5)], doors: [{ a: 'wet', b: 'dry', kind: 'sliding', width: 1100 }] }] },

  // ------------------------------------------------------------- kitchens
  { id: 'kitchen-straight', name: 'Straight kitchen', category: 'kitchens', keywords: ['kitchen', 'galley', 'straight', 'one wall', 'kitchenette'], description: 'One counter with hob and sink, plus a fridge — efficient for small homes.',
    sizes: [{ id: 'S', label: 'Compact', w: 7, d: 11, fits: '10 ft counter · fridge', parts: one('Kitchen', 'kitchen', 7, 11, { items: [{ asset: 'kitchen-run', side: 'w', along: 0.5 }, { asset: 'fridge', side: 'n', along: 0.9 }] }) },
      { id: 'M', label: 'Standard', w: 8, d: 14, fits: 'Long counter · fridge · storage', parts: one('Kitchen', 'kitchen', 8, 14, { items: [{ asset: 'kitchen-run', side: 'w', along: 0.05 }, { asset: 'fridge', side: 'w', along: 0.97 }] }) }] },
  { id: 'kitchen-l', name: 'L-shaped kitchen', category: 'kitchens', keywords: ['kitchen', 'l shaped', 'l kitchen'], description: 'Hob counter on one wall, sink on the next — the classic work triangle.',
    sizes: [
      { id: 'S', label: 'Compact', w: 9, d: 11, fits: 'L counter · fridge', parts: one('Kitchen', 'kitchen', 9, 11, { items: [{ asset: 'kitchen-run', side: 'w', along: 1 }, { asset: 'kitchen-sink', side: 'n', along: 1 }, { asset: 'fridge', side: 'e', along: 0.1 }] }) },
      { id: 'M', label: 'Standard', w: 10, d: 12, fits: 'L counter · fridge · breakfast space', parts: one('Kitchen', 'kitchen', 10, 12, { items: [{ asset: 'kitchen-run', side: 'w', along: 1 }, { asset: 'kitchen-sink', side: 'n', along: 1 }, { asset: 'fridge', side: 'e', along: 0.1 }] }) },
    ] },
  { id: 'kitchen-u', name: 'U-shaped kitchen', category: 'kitchens', keywords: ['kitchen', 'u shaped', 'u kitchen'], description: 'Counters on three walls — maximum storage and workspace.',
    sizes: [{ id: 'M', label: 'Standard', w: 11, d: 11, fits: 'U counter · fridge', parts: one('Kitchen', 'kitchen', 11, 11, { items: [{ asset: 'kitchen-run', side: 'w', along: 0.5 }, { asset: 'kitchen-sink', side: 'e', along: 0.5 }, { asset: 'fridge', side: 'n', along: 0.5 }] }) },
      { id: 'L', label: 'Spacious', w: 12, d: 13, fits: 'Large U · fridge', parts: one('Kitchen', 'kitchen', 12, 13, { items: [{ asset: 'kitchen-run', side: 'w', along: 0.5 }, { asset: 'kitchen-sink', side: 'e', along: 0.5 }, { asset: 'fridge', side: 'n', along: 0.5 }] }) }] },
  { id: 'kitchen-parallel', name: 'Parallel kitchen', category: 'kitchens', keywords: ['kitchen', 'parallel', 'galley', 'two wall'], description: 'Two facing counters — hob on one side, sink on the other.',
    sizes: [{ id: 'S', label: 'Standard', w: 8.5, d: 12, fits: 'Two counters · fridge', parts: one('Kitchen', 'kitchen', 8.5, 12, { items: [{ asset: 'kitchen-run', side: 'w', along: 0.5 }, { asset: 'kitchen-sink', side: 'e', along: 0.6 }, { asset: 'fridge', side: 'e', along: 0.02 }] }) },
      { id: 'M', label: 'Long', w: 9, d: 15, fits: 'Two long counters · fridge', parts: one('Kitchen', 'kitchen', 9, 15, { items: [{ asset: 'kitchen-run', side: 'w', along: 0.5 }, { asset: 'kitchen-sink', side: 'e', along: 0.7 }, { asset: 'fridge', side: 'e', along: 0.02 }] }) }] },
  { id: 'kitchen-island', name: 'Island kitchen', category: 'kitchens', keywords: ['kitchen', 'island', 'open kitchen', 'modular'], description: 'Wall counter, sink and a central island for cooking with family.',
    sizes: [{ id: 'M', label: 'Standard', w: 13, d: 14, fits: 'Counter · island · fridge', parts: one('Kitchen', 'kitchen', 13, 14, { items: [{ asset: 'kitchen-run', side: 'w', along: 0.6 }, { asset: 'kitchen-sink', side: 'n', along: 0.75 }, { asset: 'fridge', side: 'w', along: 0.02 }, { asset: 'island', side: 'center', along: 0.6, rot: 90 }] }) },
      { id: 'L', label: 'Chef', w: 15, d: 16, fits: 'Long counter · large island · fridge', parts: one('Kitchen', 'kitchen', 15, 16, { items: [{ asset: 'kitchen-run', side: 'w', along: 0.6 }, { asset: 'kitchen-sink', side: 'n', along: 0.7 }, { asset: 'fridge', side: 'w', along: 0.02 }, { asset: 'island', side: 'center', along: 0.6, rot: 90 }] }) }] },
  { id: 'kitchen-utility', name: 'Kitchen + utility', category: 'kitchens', keywords: ['kitchen', 'utility', 'wash area', 'laundry'], description: 'Kitchen with an attached wash and laundry area.',
    sizes: [{ id: 'M', label: 'Standard', w: 15, d: 11, fits: 'Kitchen · washing machine', parts: [P('k', 'Kitchen', 'kitchen', 0, 0, 10, 11), P('u', 'Utility', 'utility', 10, 0, 5, 11)], doors: [{ a: 'u', b: 'k' }] }] },
  { id: 'kitchen-dining', name: 'Open kitchen + dining', category: 'kitchens', keywords: ['open kitchen', 'kitchen dining', 'open plan'], description: 'Kitchen opening straight into a six-seat dining room.',
    sizes: [{ id: 'M', label: 'Standard', w: 22, d: 12, fits: 'L kitchen · 6-seat dining', parts: [P('k', 'Kitchen', 'kitchen', 0, 0, 10, 12), P('d', 'Dining', 'dining', 10, 0, 12, 12)], doors: [{ a: 'k', b: 'd', kind: 'opening', width: 1800 }] }] },

  // ------------------------------------------------------------- living
  { id: 'living', name: 'Living room', category: 'living', keywords: ['living', 'lounge', 'drawing room', 'hall'], description: 'Sofa, TV wall, coffee table and rug.',
    sizes: [{ id: 'S', label: 'Cozy', w: 12, d: 14, fits: '3-seat sofa · TV', parts: one('Living Room', 'living', 12, 14) }, { id: 'M', label: 'Standard', w: 14, d: 18, fits: 'L-sofa · TV · armchair', parts: one('Living Room', 'living', 14, 18) }, { id: 'L', label: 'Grand', w: 18, d: 22, fits: 'L-sofa · armchairs · TV', parts: one('Living Room', 'living', 18, 22) }] },
  { id: 'living-dining', name: 'Living + dining (open plan)', category: 'living', keywords: ['living dining', 'open plan', 'hall', 'great room'], description: 'One connected space for sitting and eating.',
    sizes: [
      { id: 'S', label: 'Cozy', w: 14, d: 22, fits: 'Sofa · TV · 4-seat dining', parts: [P('l', 'Living Room', 'living', 0, 0, 14, 12), P('d', 'Dining', 'dining', 0, 12, 14, 10)], doors: [{ a: 'd', b: 'l', kind: 'opening', width: 2400 }] },
      { id: 'M', label: 'Standard', w: 16, d: 26, fits: 'L-sofa · TV · 6-seat dining', parts: [P('l', 'Living Room', 'living', 0, 0, 16, 15), P('d', 'Dining', 'dining', 0, 15, 16, 11)], doors: [{ a: 'd', b: 'l', kind: 'opening', width: 3000 }] },
      { id: 'L', label: 'Grand', w: 18, d: 30, fits: 'L-sofa · armchairs · 8-seat dining', parts: [P('l', 'Living Room', 'living', 0, 0, 18, 17), P('d', 'Dining', 'dining', 0, 17, 18, 13, { items: [{ asset: 'dining-8', side: 'center', along: 0.5 }] })], doors: [{ a: 'd', b: 'l', kind: 'opening', width: 3600 }] },
    ] },
  { id: 'dining', name: 'Dining room', category: 'living', keywords: ['dining', 'dinner', 'eating'], description: 'Table and chairs sized for your family.',
    sizes: [{ id: 'S', label: '4 seats', w: 9.5, d: 10.5, fits: '4-seat table', parts: one('Dining', 'dining', 9.5, 10.5) }, { id: 'M', label: '6 seats', w: 11, d: 12, fits: '6-seat table', parts: one('Dining', 'dining', 11, 12) }, { id: 'L', label: '8 seats', w: 12, d: 16, fits: '8-seat table', parts: one('Dining', 'dining', 12, 16, { items: [{ asset: 'dining-8', side: 'center', along: 0.5, rot: 90 }] }) }] },
  { id: 'family', name: 'Family lounge', category: 'living', keywords: ['family', 'lounge', 'tv room', 'upper lounge'], description: 'A relaxed TV lounge, perfect on upper floors.',
    sizes: [{ id: 'S', label: 'Cozy', w: 11, d: 12, fits: 'Sofa · TV', parts: one('Family Lounge', 'family', 11, 12) }, { id: 'M', label: 'Standard', w: 14, d: 15, fits: 'Sofa · TV · games', parts: one('Family Lounge', 'family', 14, 15) }] },
  { id: 'theatre', name: 'Home theatre', category: 'living', keywords: ['theatre', 'theater', 'cinema', 'media room', 'movie'], description: 'Projection wall, speakers and reclining seats.',
    sizes: [{ id: 'S', label: '3 seats', w: 13, d: 16, fits: 'Screen · 3 recliners', parts: one('Home Theatre', 'media', 13, 16, { items: [{ asset: 'projector-screen', side: 'n', along: 0.5 }, { asset: 'recliner', side: 's', along: 0.5, gap: 300 }] }) },
      { id: 'M', label: '6 seats', w: 15, d: 20, fits: 'Screen · 2 rows of recliners', parts: one('Home Theatre', 'media', 15, 20, { items: [{ asset: 'projector-screen', side: 'n', along: 0.5 }, { asset: 'recliner', side: 's', along: 0.5, gap: 250 }, { asset: 'recliner', side: 'center', along: 0.5, rot: 180, gap: -200 }] }) }] },

  // ------------------------------------------------------------- work & wellness
  { id: 'office', name: 'Home office', category: 'work', keywords: ['office', 'study', 'work from home', 'library'], description: 'Desk, chair and bookshelf with daylight.',
    sizes: [{ id: 'S', label: 'Compact', w: 9.5, d: 10.5, fits: 'Desk · bookshelf', parts: one('Home Office', 'study', 9.5, 10.5) }, { id: 'M', label: 'Standard', w: 10, d: 12, fits: 'Desk · bookshelf · reading chair', parts: one('Home Office', 'study', 10, 12, { items: [{ asset: 'desk', side: 'n', along: 0.5 }, { asset: 'bookshelf', side: 'w', along: 0.4 }, { asset: 'armchair', side: 'e', along: 0.2 }] }) }] },
  { id: 'gym', name: 'Home gym', category: 'work', keywords: ['gym', 'fitness', 'workout', 'exercise'], description: 'Treadmill, weights and floor space.',
    sizes: [{ id: 'S', label: 'Compact', w: 10, d: 12, fits: 'Treadmill · weights', parts: one('Home Gym', 'gym', 10, 12, { items: [{ asset: 'treadmill', side: 'w', along: 0.9 }, { asset: 'gym-bench', side: 'e', along: 0.15 }] }) },
      { id: 'M', label: 'Studio', w: 12, d: 16, fits: 'Treadmill · weights · mat area', parts: one('Home Gym', 'gym', 12, 16, { items: [{ asset: 'treadmill', side: 'w', along: 0.9 }, { asset: 'gym-bench', side: 'e', along: 0.9 }, { asset: 'yoga-mat', side: 's', along: 0.5, gap: 200 }] }) }] },
  { id: 'yoga', name: 'Yoga & meditation', category: 'work', keywords: ['yoga', 'meditation', 'wellness', 'calm'], description: 'A calm, open room with mats and plants.',
    sizes: [{ id: 'S', label: 'Standard', w: 10, d: 11, fits: 'Mats · plants', parts: one('Yoga Room', 'gym', 10, 11, { items: [{ asset: 'yoga-mat', side: 'center', along: 0.5 }, { asset: 'plant-indoor', side: 'n', along: 0.95 }, { asset: 'plant-indoor', side: 'n', along: 0.05 }] }) }] },
  { id: 'pooja', name: 'Pooja room', category: 'work', keywords: ['pooja', 'puja', 'mandir', 'prayer', 'temple'], description: 'A dedicated prayer space with a mandir unit.',
    sizes: [{ id: 'S', label: 'Niche', w: 4.5, d: 5, fits: 'Mandir unit', parts: one('Pooja', 'pooja', 4.5, 5) }, { id: 'M', label: 'Room', w: 6, d: 7, fits: 'Mandir · seating', parts: one('Pooja', 'pooja', 6, 7) }, { id: 'L', label: 'Spacious', w: 8, d: 9, fits: 'Mandir · family seating', parts: one('Pooja', 'pooja', 8, 9) }] },

  // ------------------------------------------------------------- utility
  { id: 'utility', name: 'Utility & laundry', category: 'utility', keywords: ['utility', 'laundry', 'wash', 'washing machine'], description: 'Washing machine, drying and cleaning storage.',
    sizes: [{ id: 'S', label: 'Compact', w: 5, d: 7, fits: 'Washer', parts: one('Utility', 'utility', 5, 7) }, { id: 'M', label: 'Standard', w: 6, d: 9, fits: 'Washer · storage', parts: one('Utility', 'utility', 6, 9, { items: [{ asset: 'washer', side: 'w', along: 0.1 }, { asset: 'linen-cabinet', side: 'e', along: 0.6 }] }) }] },
  { id: 'store', name: 'Store room', category: 'utility', keywords: ['store', 'storage', 'pantry', 'box room'], description: 'Shelving for bulk storage.',
    sizes: [{ id: 'S', label: 'Small', w: 5, d: 6, fits: 'Shelving', parts: one('Store', 'store', 5, 6, { items: [{ asset: 'linen-cabinet', side: 'n', along: 0.5 }] }) }, { id: 'M', label: 'Large', w: 6, d: 9, fits: 'Shelving on two walls', parts: one('Store', 'store', 6, 9, { items: [{ asset: 'linen-cabinet', side: 'w', along: 0.5 }] }) }] },
  { id: 'walkin', name: 'Walk-in wardrobe', category: 'utility', keywords: ['walk-in', 'wardrobe', 'closet', 'dressing'], description: 'Hanging and shelving in a dedicated closet.',
    sizes: [{ id: 'S', label: 'Standard', w: 6, d: 7, fits: 'Wardrobe wall', parts: one('Walk-in Wardrobe', 'walkin', 6, 7) }, { id: 'M', label: 'Large', w: 7, d: 10, fits: 'Wardrobes on two walls', parts: one('Walk-in Wardrobe', 'walkin', 7, 10, { items: [{ asset: 'wardrobe', side: 'w', along: 0.5 }, { asset: 'dresser', side: 'e', along: 0.5 }] }) }] },

  // ------------------------------------------------------------- circulation
  { id: 'foyer', name: 'Entrance foyer', category: 'circulation', keywords: ['foyer', 'entrance', 'entry', 'lobby', 'main door'], description: 'Main door, shoe cabinet and a welcoming entry.',
    sizes: [{ id: 'S', label: 'Compact', w: 7, d: 8, fits: 'Main door · shoe cabinet', parts: one('Foyer', 'foyer', 7, 8, { items: [{ asset: 'shoe-cabinet', side: 'w', along: 0.6 }] }), doors: [{ a: 'room', b: 's', kind: 'pivot', width: 1200 }] },
      { id: 'M', label: 'Standard', w: 8, d: 10, fits: 'Pivot door · console · plant', parts: one('Foyer', 'foyer', 8, 10, { items: [{ asset: 'shoe-cabinet', side: 'w', along: 0.6 }, { asset: 'plant-indoor', side: 'e', along: 0.9 }] }), doors: [{ a: 'room', b: 's', kind: 'pivot', width: 1200 }] },
      { id: 'L', label: 'Grand', w: 10, d: 12, fits: 'Double door · console · art wall', parts: one('Foyer', 'foyer', 10, 12, { items: [{ asset: 'shoe-cabinet', side: 'w', along: 0.6 }, { asset: 'plant-indoor', side: 'e', along: 0.9 }] }), doors: [{ a: 'room', b: 's', kind: 'double', width: 1500 }] }] },
  { id: 'corridor', name: 'Corridor', category: 'circulation', keywords: ['corridor', 'passage', 'hallway', 'gallery'], description: 'A passage that links rooms together.',
    sizes: [{ id: 'S', label: 'Short', w: 4, d: 12, fits: '3 ft 6 in clear', parts: one('Corridor', 'corridor', 4, 12) }, { id: 'M', label: 'Long', w: 4, d: 20, fits: '3 ft 6 in clear', parts: one('Corridor', 'corridor', 4, 20) }, { id: 'L', label: 'Gallery', w: 5, d: 24, fits: '4 ft 6 in clear', parts: one('Gallery', 'corridor', 5, 24) }] },
  { id: 'stair-u', name: 'U-shaped staircase', category: 'circulation', keywords: ['stair', 'staircase', 'u stair', 'dog-legged', 'steps'], description: 'A compact two-flight stair with a landing — the most common home stair.',
    sizes: [{ id: 'M', label: 'Standard', w: 8, d: 12, fits: '3 ft 3 in flights', parts: one('Stair', 'stair', 8, 12, { stair: 'U' }) }] },
  { id: 'stair-straight', name: 'Straight staircase', category: 'circulation', keywords: ['stair', 'staircase', 'straight stair', 'single flight'], description: 'A single straight flight — needs length but no landing.',
    sizes: [{ id: 'M', label: 'Standard', w: 4.5, d: 17, fits: '3 ft 3 in wide flight', parts: one('Stair', 'stair', 4.5, 17, { stair: 'straight' }) }] },
  { id: 'stair-l', name: 'L-shaped staircase', category: 'circulation', keywords: ['stair', 'staircase', 'l stair', 'corner stair'], description: 'Two flights turning a corner — fits along two walls.',
    sizes: [{ id: 'M', label: 'Standard', w: 12, d: 11, fits: '3 ft 3 in flights · corner landing', parts: one('Stair', 'stair', 12, 11, { stair: 'L' }) }] },
  { id: 'lift-core', name: 'Lift + stair core', category: 'circulation', keywords: ['lift', 'elevator', 'core', 'stair and lift'], description: 'A home lift beside a U-stair with a shared lobby.',
    sizes: [{ id: 'M', label: 'Standard', w: 14, d: 12, fits: '4-person lift · U-stair', parts: [P('lift', 'Lift', 'other', 0, 6, 6, 6, { furnish: false }), P('lobby', 'Lift Lobby', 'corridor', 0, 0, 6, 6), P('stair', 'Stair', 'stair', 6, 0, 8, 12, { stair: 'U' })], doors: [{ a: 'lift', b: 'lobby', kind: 'sliding', width: 900 }, { a: 'stair', b: 'lobby', kind: 'opening', width: 1000 }] }], entry: 'lobby' },

  // ------------------------------------------------------------- outdoor
  { id: 'balcony', name: 'Balcony', category: 'outdoor', keywords: ['balcony', 'verandah', 'sit out', 'deck'], description: 'An open balcony with railing, a swing and planters.', entryDoor: 'sliding',
    sizes: [
      { id: 'S', label: 'Narrow', w: 10, d: 4, fits: 'Planters', parts: one('Balcony', 'balcony', 10, 4, { open: ['n', 'e', 'w'], items: [{ asset: 'planter-box', side: 'n', along: 0.5 }] }) },
      { id: 'M', label: 'Standard', w: 12, d: 5, fits: 'Swing · planters', parts: one('Balcony', 'balcony', 12, 5, { open: ['n', 'e', 'w'], items: [{ asset: 'swing', side: 'w', along: 0.5, rot: 0 }, { asset: 'planter-box', side: 'n', along: 0.9 }] }) },
      { id: 'L', label: 'Deep', w: 16, d: 7, fits: 'Swing · seating · planters', parts: one('Balcony', 'balcony', 16, 7, { open: ['n', 'e', 'w'], items: [{ asset: 'swing', side: 'w', along: 0.5 }, { asset: 'armchair', side: 'e', along: 0.5 }, { asset: 'planter-box', side: 'n', along: 0.5 }] }) },
    ] },
  // ------------------------------------------------------------- parking
  { id: 'car-parking', name: 'Open car parking', category: 'parking', keywords: ['parking', 'car', 'car park', 'bay', 'ecs', 'car porch', 'open parking'], description: 'Paved bays at the standard car-space size (2.5 × 5 m / 8 × 16 ft plus door clearance). Counts towards required parking.', siteOnly: true,
    sizes: [
      { id: 'S', label: '1 car', w: 9, d: 18, fits: '1 bay · 9 × 18 ft (2.7 × 5.5 m)', parts: [], site: [{ kind: 'parking', name: '1-car parking', x: 0, y: 0, w: 9, h: 18, material: 'paver', cars: 1 }], props: [{ asset: 'car-suv', x: 4.5, y: 9, variant: 'white' }] },
      { id: 'M', label: '2 cars', w: 18, d: 18, fits: '2 bays side by side · 18 × 18 ft', parts: [], site: [{ kind: 'parking', name: '2-car parking', x: 0, y: 0, w: 18, h: 18, material: 'paver', cars: 2 }], props: [{ asset: 'car-suv', x: 4.5, y: 9, variant: 'white' }, { asset: 'car-sedan', x: 13.5, y: 9, variant: 'black' }] },
      { id: 'L', label: '3 cars', w: 27, d: 18, fits: '3 bays side by side · 27 × 18 ft', parts: [], site: [{ kind: 'parking', name: '3-car parking', x: 0, y: 0, w: 27, h: 18, material: 'paver', cars: 3 }], props: [{ asset: 'car-suv', x: 4.5, y: 9, variant: 'white' }, { asset: 'car-sedan', x: 13.5, y: 9, variant: 'black' }, { asset: 'car-sedan', x: 22.5, y: 9, variant: 'silver' }] },
    ] },
  { id: 'tandem-parking', name: 'Tandem parking', category: 'parking', keywords: ['tandem', 'tandem parking', 'narrow plot parking', 'one behind'], description: 'Two cars one behind the other — the space-saver for narrow plots.', siteOnly: true,
    sizes: [{ id: 'M', label: '2 cars', w: 9, d: 34, fits: '2 bays in line · 9 × 34 ft', parts: [], site: [{ kind: 'parking', name: 'Tandem parking', x: 0, y: 0, w: 9, h: 34, material: 'paver', cars: 2 }], props: [{ asset: 'car-suv', x: 4.5, y: 8.5, variant: 'white' }, { asset: 'car-sedan', x: 4.5, y: 25.5, variant: 'black' }] }] },
  { id: 'garage', name: 'Garage', category: 'parking', keywords: ['garage', 'car', 'parking', 'covered parking', 'car shed'], description: 'An enclosed garage with a roll-up door, built into the house.', entry: 'room',
    sizes: [{ id: 'S', label: '1 car', w: 12, d: 20, fits: 'One SUV with storage', parts: one('Garage', 'parking', 12, 20, { items: [{ asset: 'car-suv', side: 'center', along: 0.5 }] }), doors: [{ a: 'room', b: 's', kind: 'garage', width: 2700 }] },
      { id: 'M', label: '2 cars', w: 20, d: 20, fits: 'Two cars side by side', parts: one('Garage', 'parking', 20, 20, { items: [{ asset: 'car-suv', side: 'center', along: 0.15 }, { asset: 'car-sedan', side: 'center', along: 0.85 }] }), doors: [{ a: 'room', b: 's', kind: 'garage', width: 5000 }] }] },
  { id: 'two-wheeler', name: 'Two-wheeler parking', category: 'parking', keywords: ['bike', 'scooter', 'two wheeler', 'motorcycle', 'cycle'], description: 'Paved bay for scooters and motorbikes (1 × 2 m each).', siteOnly: true,
    sizes: [{ id: 'S', label: '2 bikes', w: 7, d: 7, fits: '2 two-wheelers', parts: [], site: [{ kind: 'parking', name: 'Two-wheeler bay', x: 0, y: 0, w: 7, h: 7, material: 'paver' }], props: [{ asset: 'scooter', x: 2, y: 3.5, variant: 'red' }, { asset: 'scooter', x: 5, y: 3.5, variant: 'black' }] },
      { id: 'M', label: '4 bikes', w: 13, d: 7, fits: '4 two-wheelers', parts: [], site: [{ kind: 'parking', name: 'Two-wheeler bay', x: 0, y: 0, w: 13, h: 7, material: 'paver' }], props: [{ asset: 'scooter', x: 2, y: 3.5, variant: 'red' }, { asset: 'scooter', x: 5, y: 3.5, variant: 'black' }, { asset: 'scooter', x: 8, y: 3.5, variant: 'red' }, { asset: 'scooter', x: 11, y: 3.5, variant: 'black' }] }] },
  { id: 'driveway', name: 'Driveway', category: 'parking', keywords: ['driveway', 'drive', 'access road', 'entry drive', 'ramp'], description: 'A paved drive from the gate to your parking.', siteOnly: true,
    sizes: [{ id: 'S', label: 'Short', w: 10, d: 16, fits: '10 ft wide', parts: [], site: [{ kind: 'driveway', name: 'Driveway', x: 0, y: 0, w: 10, h: 16, material: 'paver' }] },
      { id: 'M', label: 'Long', w: 10, d: 30, fits: '10 ft wide', parts: [], site: [{ kind: 'driveway', name: 'Driveway', x: 0, y: 0, w: 10, h: 30, material: 'paver' }] },
      { id: 'L', label: 'Wide', w: 14, d: 30, fits: '14 ft wide · two-way', parts: [], site: [{ kind: 'driveway', name: 'Driveway', x: 0, y: 0, w: 14, h: 30, material: 'paver' }] }] },

  { id: 'pool', name: 'Swimming pool', category: 'outdoor', keywords: ['pool', 'swimming pool', 'lap pool', 'plunge pool'], description: 'A tiled pool with a timber deck and loungers.', siteOnly: true,
    sizes: [
      { id: 'S', label: 'Plunge', w: 14, d: 24, fits: '10 × 18 ft pool', parts: [], site: [{ kind: 'deck', name: 'Pool deck', x: 0, y: 0, w: 14, h: 5, material: 'deck-wood' }, { kind: 'pool', name: 'Plunge pool', x: 2, y: 5.5, w: 10, h: 18, material: 'pool-water' }], props: [{ asset: 'lounger', x: 4, y: 2.3, rot: 90 }, { asset: 'lounger', x: 10, y: 2.3, rot: 90 }] },
      { id: 'M', label: 'Lap', w: 18, d: 36, fits: '12 × 28 ft lap pool', parts: [], site: [{ kind: 'deck', name: 'Pool deck', x: 0, y: 0, w: 18, h: 7, material: 'deck-wood' }, { kind: 'pool', name: 'Lap pool', x: 3, y: 7.5, w: 12, h: 28, material: 'pool-water' }], props: [{ asset: 'lounger', x: 4, y: 3.3, rot: 90 }, { asset: 'lounger', x: 9, y: 3.3, rot: 90 }, { asset: 'lounger', x: 14, y: 3.3, rot: 90 }] },
      { id: 'L', label: 'Resort', w: 24, d: 42, fits: '16 × 32 ft pool', parts: [], site: [{ kind: 'deck', name: 'Pool deck', x: 0, y: 0, w: 24, h: 9, material: 'deck-wood' }, { kind: 'pool', name: 'Swimming pool', x: 4, y: 9.5, w: 16, h: 32, material: 'pool-water' }], props: [{ asset: 'lounger-pair', x: 6, y: 4.5 }, { asset: 'parasol', x: 6, y: 5.4 }, { asset: 'outdoor-dining', x: 18, y: 4.5 }, { asset: PL('pygmy-date'), x: 1.6, y: 12 }, { asset: PL('pygmy-date'), x: 22.4, y: 12 }] },
    ] },
  { id: 'deck', name: 'Timber deck', category: 'outdoor', keywords: ['deck', 'timber deck', 'terrace', 'dining deck'], description: 'A raised hardwood deck set for outdoor dining.', siteOnly: true,
    sizes: [{ id: 'S', label: 'Dining for 4', w: 14, d: 12, fits: 'Outdoor dining for 4', parts: [], site: [{ kind: 'deck', name: 'Deck', x: 0, y: 0, w: 14, h: 12, material: 'deck-wood' }], props: [{ asset: 'outdoor-dining', x: 7, y: 6 }, { asset: PL('areca'), x: 1.5, y: 10.5 }] },
      { id: 'M', label: 'Dining for 6', w: 18, d: 14, fits: 'Dining for 6 · parasol', parts: [], site: [{ kind: 'deck', name: 'Deck', x: 0, y: 0, w: 18, h: 14, material: 'deck-wood' }], props: [{ asset: 'outdoor-dining-6', x: 9, y: 7 }, { asset: 'parasol', x: 9, y: 7.4 }, { asset: PL('areca'), x: 1.5, y: 12.5 }, { asset: PL('bird-of-paradise'), x: 16.5, y: 12.5 }] }] },
  { id: 'patio', name: 'Stone patio', category: 'outdoor', keywords: ['patio', 'terrace', 'paved', 'alfresco', 'dining', 'courtyard'], description: 'A paved terrace with dining — the classic step out from the living room.', siteOnly: true,
    sizes: [{ id: 'S', label: 'Breakfast', w: 10, d: 10, fits: 'Bistro table for 2', parts: [], site: [{ kind: 'patio', name: 'Patio', x: 0, y: 0, w: 10, h: 10, material: 'sandstone-paving' }], props: [{ asset: 'bistro-set', x: 5, y: 5 }, { asset: PL('boxwood'), x: 1.2, y: 8.8 }, { asset: PL('boxwood'), x: 8.8, y: 8.8 }] },
      { id: 'M', label: 'Dining for 6', w: 16, d: 14, fits: 'Dining for 6 · parasol', parts: [], site: [{ kind: 'patio', name: 'Patio', x: 0, y: 0, w: 16, h: 14, material: 'sandstone-paving' }], props: [{ asset: 'outdoor-dining-6', x: 8, y: 7 }, { asset: 'parasol', x: 8, y: 7.4 }, { asset: PL('boxwood'), x: 1.3, y: 12.7 }, { asset: PL('boxwood'), x: 14.7, y: 12.7 }] },
      { id: 'L', label: 'Entertaining', w: 22, d: 18, fits: 'Dining for 8 · barbecue', parts: [], site: [{ kind: 'patio', name: 'Patio', x: 0, y: 0, w: 22, h: 18, material: 'travertine' }], props: [{ asset: 'outdoor-dining-8', x: 8, y: 9 }, { asset: 'bbq', x: 18.5, y: 15.5 }, { asset: 'outdoor-lounge', x: 17.5, y: 5 }, { asset: PL('pygmy-date'), x: 1.6, y: 16.4 }, { asset: PL('pygmy-date'), x: 20.4, y: 1.6 }] }] },
  { id: 'sit-out', name: 'Pergola sit-out', category: 'outdoor', keywords: ['sit-out', 'sit out', 'sitout', 'pergola', 'lounge', 'verandah', 'outdoor seating', 'seating'], description: 'An outdoor living room: a sofa set in the shade of a pergola.', siteOnly: true,
    sizes: [{ id: 'S', label: 'Cosy', w: 12, d: 12, fits: 'Two lounge chairs · pergola', parts: [], site: [{ kind: 'patio', name: 'Sit-out', x: 0, y: 0, w: 12, h: 12, material: 'terracotta-paver' }], props: [{ asset: 'pergola', x: 6, y: 6 }, { asset: 'outdoor-lounge', x: 6, y: 6.5 }, { asset: PL('jasmine'), x: 1.2, y: 10.8 }, { asset: PL('madhumalti'), x: 10.8, y: 10.8 }] },
      { id: 'M', label: 'Family', w: 18, d: 14, fits: 'Sectional sofa · pergola', parts: [], site: [{ kind: 'patio', name: 'Sit-out', x: 0, y: 0, w: 18, h: 14, material: 'sandstone-paving' }], props: [{ asset: 'pergola-l', x: 9, y: 7 }, { asset: 'outdoor-sofa', x: 9, y: 7.6 }, { asset: PL('areca'), x: 1.4, y: 12.6 }, { asset: PL('madhumalti'), x: 16.6, y: 12.6 }, { asset: 'bollard-light', x: 1, y: 1 }, { asset: 'bollard-light', x: 17, y: 1 }] },
      { id: 'L', label: 'Lounge + fire', w: 24, d: 16, fits: 'Sofa · fire table · day chairs', parts: [], site: [{ kind: 'patio', name: 'Sit-out', x: 0, y: 0, w: 24, h: 16, material: 'granite-paving' }], props: [{ asset: 'pergola-l', x: 9, y: 8 }, { asset: 'outdoor-sofa', x: 9, y: 8.8 }, { asset: 'fire-table', x: 19.5, y: 8 }, { asset: 'outdoor-lounge', x: 19.5, y: 12.5, rot: 180 }, { asset: PL('giant-strelitzia'), x: 1.6, y: 14.4 }, { asset: PL('bird-of-paradise'), x: 22.4, y: 1.6 }, { asset: 'bollard-light', x: 1, y: 1 }, { asset: 'bollard-light', x: 23, y: 15 }] }] },
  { id: 'fire-pit-court', name: 'Fire pit circle', category: 'outdoor', keywords: ['fire pit', 'firepit', 'bonfire', 'fire', 'gathering'], description: 'A gravel court around a fire pit — the after-dinner spot.', siteOnly: true,
    sizes: [{ id: 'S', label: 'For 4', w: 12, d: 12, fits: 'Fire pit · 2 benches', parts: [], site: [{ kind: 'gravel', name: 'Fire pit court', x: 0, y: 0, w: 12, h: 12, material: 'gravel' }], props: [{ asset: 'fire-pit', x: 6, y: 6 }, { asset: 'garden-bench', x: 6, y: 10.6 }, { asset: 'garden-bench', x: 6, y: 1.4, rot: 180 }] },
      { id: 'M', label: 'For 8', w: 16, d: 16, fits: 'Fire pit · 4 benches · boulders', parts: [], site: [{ kind: 'gravel', name: 'Fire pit court', x: 0, y: 0, w: 16, h: 16, material: 'gravel' }], props: [{ asset: 'fire-pit', x: 8, y: 8 }, { asset: 'garden-bench', x: 8, y: 14.4 }, { asset: 'garden-bench', x: 8, y: 1.6, rot: 180 }, { asset: 'garden-bench', x: 1.6, y: 8, rot: 90 }, { asset: 'garden-bench', x: 14.4, y: 8, rot: 270 }, { asset: PL('fountain-grass'), x: 1.6, y: 14.4 }, { asset: PL('fountain-grass'), x: 14.4, y: 14.4 }, { asset: PL('fountain-grass'), x: 1.6, y: 1.6 }, { asset: PL('fountain-grass'), x: 14.4, y: 1.6 }] }] },
  { id: 'outdoor-kitchen-court', name: 'Outdoor kitchen', category: 'outdoor', keywords: ['outdoor kitchen', 'bbq', 'barbecue', 'grill', 'bar', 'alfresco kitchen'], description: 'Cook and serve outside: counter, grill, sink and a bar to lean on.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Cook + bar', w: 18, d: 12, fits: 'L-kitchen · bar with 3 stools', parts: [], site: [{ kind: 'patio', name: 'Outdoor kitchen', x: 0, y: 0, w: 18, h: 12, material: 'granite-paving' }], props: [{ asset: 'outdoor-kitchen', x: 6, y: 7.5 }, { asset: 'bar-counter', x: 13.5, y: 3, rot: 180 }] },
      { id: 'L', label: 'Cook + dine', w: 26, d: 16, fits: 'Kitchen · oven · dining for 6 under a pergola', parts: [], site: [{ kind: 'patio', name: 'Outdoor kitchen', x: 0, y: 0, w: 26, h: 16, material: 'granite-paving' }], props: [{ asset: 'outdoor-kitchen', x: 6, y: 11 }, { asset: 'pizza-oven', x: 2.6, y: 2.6 }, { asset: 'pergola-l', x: 17, y: 8 }, { asset: 'outdoor-dining-6', x: 17, y: 8 }] }] },
  { id: 'spa-deck', name: 'Jacuzzi deck', category: 'outdoor', keywords: ['jacuzzi', 'spa', 'hot tub', 'plunge', 'wellness'], description: 'A sunken-style spa with loungers and an outdoor shower.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 16, d: 14, fits: 'Jacuzzi · loungers · shower', parts: [], site: [{ kind: 'deck', name: 'Spa deck', x: 0, y: 0, w: 16, h: 14, material: 'composite-deck' }], props: [{ asset: 'jacuzzi', x: 4.6, y: 9.4 }, { asset: 'lounger-pair', x: 11.6, y: 9 }, { asset: 'outdoor-shower', x: 2, y: 2 }, { asset: PL('bamboo'), x: 14.4, y: 1.8 }, { asset: PL('monstera'), x: 8, y: 1.8 }] }] },
  { id: 'cabana', name: 'Daybed cabana', category: 'outdoor', keywords: ['cabana', 'daybed', 'pool', 'lounge', 'resort'], description: 'A canopy daybed framed by palms — resort corner by the pool.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 12, d: 11, fits: 'Canopy daybed · palms', parts: [], site: [{ kind: 'deck', name: 'Cabana', x: 0, y: 0, w: 12, h: 11, material: 'deck-wood' }], props: [{ asset: 'daybed', x: 6, y: 6 }, { asset: PL('areca'), x: 1.3, y: 9.6 }, { asset: PL('areca'), x: 10.7, y: 9.6 }] }] },
  { id: 'gazebo-court', name: 'Gazebo', category: 'outdoor', keywords: ['gazebo', 'pavilion', 'garden room', 'summer house'], description: 'A roofed pavilion in the garden with a bench and lanterns.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 18, d: 18, fits: '12 ft gazebo · path lights', parts: [], site: [{ kind: 'patio', name: 'Gazebo court', x: 0, y: 0, w: 18, h: 18, material: 'crazy-paving' }], props: [{ asset: 'gazebo', x: 9, y: 9 }, { asset: 'garden-bench', x: 9, y: 11.6 }, { asset: 'bollard-light', x: 1.2, y: 1.2 }, { asset: 'bollard-light', x: 16.8, y: 1.2 }, { asset: PL('hibiscus'), x: 1.6, y: 16.4 }, { asset: PL('hibiscus'), x: 16.4, y: 16.4 }] }] },
  { id: 'yoga-deck', name: 'Yoga deck', category: 'outdoor', keywords: ['yoga', 'meditation', 'wellness', 'deck', 'exercise'], description: 'A quiet timber platform screened by bamboo.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 14, d: 12, fits: 'Mats for 2 · bamboo screen', parts: [], site: [{ kind: 'deck', name: 'Yoga deck', x: 0, y: 0, w: 14, h: 12, material: 'composite-deck' }], props: [{ asset: 'yoga-mat', x: 7, y: 5 }, { asset: PL('bamboo'), x: 2, y: 10.4 }, { asset: PL('bamboo'), x: 7, y: 10.6 }, { asset: PL('bamboo'), x: 12, y: 10.4 }] }] },
  { id: 'kids-play', name: 'Children’s play area', category: 'outdoor', keywords: ['kids', 'children', 'play', 'playground', 'swing', 'slide', 'sandpit'], description: 'Soft-fall turf with a swing and slide, a sand pit and a bench for the grown-ups.', siteOnly: true,
    sizes: [{ id: 'S', label: 'Compact', w: 16, d: 12, fits: 'Sand pit · trampoline', parts: [], site: [{ kind: 'lawn', name: 'Play lawn', x: 0, y: 0, w: 16, h: 12, material: 'artificial-turf' }], props: [{ asset: 'sandpit', x: 4, y: 6 }, { asset: 'trampoline', x: 11, y: 6 }] },
      { id: 'M', label: 'Full', w: 24, d: 18, fits: 'Swing + slide · sand pit · bench', parts: [], site: [{ kind: 'lawn', name: 'Play lawn', x: 0, y: 0, w: 24, h: 18, material: 'artificial-turf' }], props: [{ asset: 'play-set', x: 9, y: 10 }, { asset: 'sandpit', x: 19.5, y: 12.5 }, { asset: 'garden-bench', x: 19, y: 2, rot: 180 }, { asset: PL('ficus'), x: 2, y: 2 }] }] },
  { id: 'carport-bay', name: 'Covered car porch', category: 'parking', keywords: ['carport', 'car porch', 'covered parking', 'porch', 'shade parking'], description: 'A roofed bay on pavers with an EV charging point. Counts towards required parking.', siteOnly: true,
    sizes: [{ id: 'S', label: '1 car', w: 11, d: 19, fits: '1 covered bay · EV charger', parts: [], site: [{ kind: 'parking', name: 'Car porch', x: 0, y: 0, w: 11, h: 19, material: 'cobble', cars: 1 }], props: [{ asset: 'carport', x: 5.5, y: 9.5 }, { asset: 'car-suv', x: 5.5, y: 9.5, variant: 'white' }, { asset: 'ev-charger', x: 1, y: 17.8 }] },
      { id: 'M', label: '2 cars', w: 20, d: 19, fits: '2 covered bays · EV charger', parts: [], site: [{ kind: 'parking', name: 'Car porch', x: 0, y: 0, w: 20, h: 19, material: 'cobble', cars: 2 }], props: [{ asset: 'carport-2', x: 10, y: 9.5 }, { asset: 'car-suv', x: 5.5, y: 9.5, variant: 'white' }, { asset: 'car-sedan', x: 14.5, y: 9.5, variant: 'black' }, { asset: 'ev-charger', x: 10, y: 17.8 }] }] },
  { id: 'entrance-court', name: 'Entrance gate + drive', category: 'parking', keywords: ['gate', 'entrance', 'main gate', 'entry', 'drive', 'arrival'], description: 'A main gate with pillars and lanterns, cypress either side, and a cobbled apron.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 22, d: 12, fits: '13 ft gate · lanterns · cypress', parts: [], site: [{ kind: 'driveway', name: 'Entrance apron', x: 3, y: 0, w: 16, h: 12, material: 'cobble' }], props: [{ asset: 'gate-main', x: 11, y: 0.8 }, { asset: PL('cypress'), x: 1.4, y: 2 }, { asset: PL('cypress'), x: 20.6, y: 2 }, { asset: 'lamp-post', x: 1.6, y: 10.4 }, { asset: 'lamp-post', x: 20.4, y: 10.4 }] }] },
  // ---------------------------------------------------------------- gardens
  { id: 'lawn', name: 'Garden lawn', category: 'garden', keywords: ['garden', 'lawn', 'grass', 'landscape', 'trees', 'yard'], description: 'A lawn framed by a shade tree, flowering shrubs and a bench.', siteOnly: true,
    sizes: [{ id: 'S', label: 'Small', w: 16, d: 16, fits: 'Lawn · frangipani · shrubs', parts: [], site: [{ kind: 'lawn', name: 'Lawn', x: 0, y: 0, w: 16, h: 16, material: 'lawn' }], props: [{ asset: PL('frangipani'), x: 3.5, y: 12.5 }, { asset: PL('hibiscus'), x: 13.5, y: 13.5 }, { asset: PL('ixora'), x: 14, y: 2 }, { asset: PL('ixora'), x: 11.5, y: 1.8 }] },
      { id: 'M', label: 'Large', w: 28, d: 26, fits: 'Lawn · shade tree · palms · bench', parts: [], site: [{ kind: 'lawn', name: 'Lawn', x: 0, y: 0, w: 28, h: 26, material: 'lawn' }], props: [{ asset: PL('tabebuia'), x: 6, y: 20 }, { asset: PL('foxtail'), x: 24, y: 22 }, { asset: PL('foxtail'), x: 24, y: 4 }, { asset: PL('hibiscus'), x: 2.5, y: 3 }, { asset: PL('bird-of-paradise'), x: 14, y: 24 }, { asset: PL('ixora'), x: 18, y: 24.3 }, { asset: 'garden-bench', x: 7, y: 14.5, rot: 180 }, { asset: 'uplight', x: 7.6, y: 19 }] }] },
  { id: 'flower-border', name: 'Flowering border', category: 'garden', keywords: ['border', 'flower bed', 'flowers', 'planting bed', 'shrubs', 'bed'], description: 'A mulched bed layered tall to low — plant it along a wall or path.', siteOnly: true,
    sizes: [{ id: 'S', label: '12 ft', w: 12, d: 4, fits: 'Hibiscus · ixora · periwinkle', parts: [], site: [{ kind: 'bed', name: 'Planting bed', x: 0, y: 0, w: 12, h: 4, material: 'mulch' }], props: [{ asset: PL('hibiscus'), x: 2, y: 2.8 }, { asset: PL('plumbago'), x: 6, y: 2.8 }, { asset: PL('hibiscus'), x: 10, y: 2.8 }, { asset: PL('ixora'), x: 4, y: 1.3 }, { asset: PL('ixora'), x: 8, y: 1.3 }, { asset: PL('vinca'), x: 1.2, y: 0.9 }, { asset: PL('vinca'), x: 6, y: 0.8 }, { asset: PL('vinca'), x: 10.8, y: 0.9 }] },
      { id: 'M', label: '24 ft', w: 24, d: 5, fits: 'Crepe myrtle · shrubs · ground cover', parts: [], site: [{ kind: 'bed', name: 'Planting bed', x: 0, y: 0, w: 24, h: 5, material: 'mulch' }], props: [{ asset: PL('crepe-myrtle'), x: 12, y: 3.4 }, { asset: PL('hibiscus'), x: 3, y: 3.5 }, { asset: PL('tecoma'), x: 21, y: 3.5 }, { asset: PL('plumbago'), x: 7, y: 3.2 }, { asset: PL('plumbago'), x: 17, y: 3.2 }, { asset: PL('ixora'), x: 4.5, y: 1.4 }, { asset: PL('ixora'), x: 9.5, y: 1.4 }, { asset: PL('ixora'), x: 14.5, y: 1.4 }, { asset: PL('ixora'), x: 19.5, y: 1.4 }, { asset: PL('duranta'), x: 1.3, y: 1 }, { asset: PL('duranta'), x: 7, y: 0.9 }, { asset: PL('duranta'), x: 12, y: 0.9 }, { asset: PL('duranta'), x: 17, y: 0.9 }, { asset: PL('duranta'), x: 22.7, y: 1 }] }] },
  { id: 'kitchen-garden', name: 'Kitchen garden', category: 'garden', keywords: ['kitchen garden', 'vegetable', 'veggie', 'herbs', 'vegetables', 'organic', 'grow'], description: 'Raised vegetable beds with herbs and fruit — sited where it gets six hours of sun.', siteOnly: true,
    sizes: [{ id: 'S', label: '2 beds', w: 12, d: 10, fits: '2 raised beds · curry leaf · lemongrass', parts: [], site: [{ kind: 'gravel', name: 'Kitchen garden', x: 0, y: 0, w: 12, h: 10, material: 'gravel' }], props: [{ asset: 'raised-bed', x: 6, y: 7.2 }, { asset: 'raised-bed', x: 6, y: 2.8 }, { asset: PL('curry-leaf'), x: 1.3, y: 8.6 }, { asset: PL('lemongrass'), x: 10.8, y: 8.8 }, { asset: PL('tulsi'), x: 10.9, y: 1.1 }] },
      { id: 'M', label: '4 beds', w: 20, d: 14, fits: '4 raised beds · lemon · banana · herbs', parts: [], site: [{ kind: 'gravel', name: 'Kitchen garden', x: 0, y: 0, w: 20, h: 14, material: 'gravel' }], props: [{ asset: 'raised-bed', x: 5.5, y: 10.5 }, { asset: 'raised-bed', x: 14.5, y: 10.5 }, { asset: 'raised-bed', x: 5.5, y: 5 }, { asset: 'raised-bed', x: 14.5, y: 5 }, { asset: PL('lemon'), x: 1.6, y: 1.6 }, { asset: PL('banana'), x: 18.4, y: 1.8 }, { asset: PL('curry-leaf'), x: 10, y: 1.4 }, { asset: PL('lemongrass'), x: 1.2, y: 12.8 }, { asset: PL('tulsi'), x: 18.9, y: 12.9 }] }] },
  { id: 'zen-garden', name: 'Zen garden', category: 'garden', keywords: ['zen', 'japanese', 'gravel garden', 'rock garden', 'meditation', 'dry garden'], description: 'Raked gravel, boulders, a maple and a bamboo backdrop.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 16, d: 12, fits: 'Gravel · boulders · maple · bamboo', parts: [], site: [{ kind: 'gravel', name: 'Zen garden', x: 0, y: 0, w: 16, h: 12, material: 'white-pebble' }], props: [{ asset: 'boulders', x: 10.5, y: 6 }, { asset: 'stepping-stones', x: 3, y: 6 }, { asset: PL('maple'), x: 6.5, y: 9.4 }, { asset: PL('bamboo'), x: 14, y: 10.4 }, { asset: PL('mondo'), x: 9, y: 3.4 }, { asset: PL('mondo'), x: 12.4, y: 3.8 }, { asset: PL('mondo'), x: 8.2, y: 7.6 }, { asset: PL('azalea'), x: 13.8, y: 2 }] }] },
  { id: 'tropical-corner', name: 'Tropical corner', category: 'garden', keywords: ['tropical', 'palms', 'jungle', 'resort', 'lush', 'corner'], description: 'Layered palms, heliconia and ferns to soften a boundary corner.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 14, d: 14, fits: 'Coconut · areca · heliconia · ferns', parts: [], site: [{ kind: 'bed', name: 'Tropical planting', x: 0, y: 0, w: 14, h: 14, material: 'mulch' }], props: [{ asset: PL('coconut'), x: 10.6, y: 10.6 }, { asset: PL('areca'), x: 4, y: 11.4 }, { asset: PL('areca'), x: 11.4, y: 4 }, { asset: PL('heliconia'), x: 7, y: 7.6 }, { asset: PL('alocasia'), x: 3.2, y: 6.4 }, { asset: PL('giant-strelitzia'), x: 7.4, y: 12 }, { asset: PL('fern'), x: 5.4, y: 3 }, { asset: PL('fern'), x: 2, y: 2.6 }, { asset: PL('spider-lily'), x: 8.6, y: 2 }, { asset: PL('spider-lily'), x: 2, y: 9.4 }, { asset: 'uplight', x: 9.6, y: 9.4 }] }] },
  { id: 'palm-avenue', name: 'Palm avenue', category: 'garden', keywords: ['avenue', 'palm row', 'driveway palms', 'row of palms', 'palms'], description: 'A formal row of palms with uplights — line a drive or a boundary.', siteOnly: true,
    sizes: [{ id: 'S', label: '3 palms', w: 6, d: 30, fits: '3 foxtail palms · uplights', parts: [], site: [{ kind: 'bed', name: 'Palm avenue', x: 0, y: 0, w: 6, h: 30, material: 'white-pebble' }], props: [{ asset: PL('foxtail'), x: 3, y: 5 }, { asset: PL('foxtail'), x: 3, y: 15 }, { asset: PL('foxtail'), x: 3, y: 25 }, { asset: 'uplight', x: 3, y: 7.4 }, { asset: 'uplight', x: 3, y: 17.4 }, { asset: 'uplight', x: 3, y: 27.4 }] },
      { id: 'M', label: '5 palms', w: 7, d: 60, fits: '5 royal palms · uplights', parts: [], site: [{ kind: 'bed', name: 'Palm avenue', x: 0, y: 0, w: 7, h: 60, material: 'white-pebble' }], props: [{ asset: PL('royal-palm'), x: 3.5, y: 6 }, { asset: PL('royal-palm'), x: 3.5, y: 18 }, { asset: PL('royal-palm'), x: 3.5, y: 30 }, { asset: PL('royal-palm'), x: 3.5, y: 42 }, { asset: PL('royal-palm'), x: 3.5, y: 54 }, { asset: 'uplight', x: 3.5, y: 9 }, { asset: 'uplight', x: 3.5, y: 21 }, { asset: 'uplight', x: 3.5, y: 33 }, { asset: 'uplight', x: 3.5, y: 45 }, { asset: 'uplight', x: 3.5, y: 57 }] }] },
  { id: 'bamboo-screen', name: 'Bamboo privacy screen', category: 'garden', keywords: ['privacy', 'screen', 'bamboo', 'hedge', 'boundary planting', 'neighbours'], description: 'A fast, tall green wall against an overlooked boundary.', siteOnly: true,
    sizes: [{ id: 'S', label: '16 ft', w: 16, d: 4, fits: '4 bamboo clumps', parts: [], site: [{ kind: 'bed', name: 'Bamboo screen', x: 0, y: 0, w: 16, h: 4, material: 'mulch' }], props: [2, 6, 10, 14].map((x) => ({ asset: PL('bamboo'), x, y: 2 })) },
      { id: 'M', label: '32 ft', w: 32, d: 4, fits: '8 bamboo clumps', parts: [], site: [{ kind: 'bed', name: 'Bamboo screen', x: 0, y: 0, w: 32, h: 4, material: 'mulch' }], props: [2, 6, 10, 14, 18, 22, 26, 30].map((x) => ({ asset: PL('bamboo'), x, y: 2 })) }] },
  { id: 'ashoka-screen', name: 'Ashoka tree line', category: 'garden', keywords: ['ashoka', 'tree line', 'boundary trees', 'screen', 'privacy'], description: 'Slender evergreen columns at 6 ft centres — the classic compound-wall screen.', siteOnly: true,
    sizes: [{ id: 'M', label: '30 ft', w: 30, d: 4, fits: '5 ashoka trees', parts: [], site: [{ kind: 'bed', name: 'Tree line', x: 0, y: 0, w: 30, h: 4, material: 'mulch' }], props: [3, 9, 15, 21, 27].map((x) => ({ asset: PL('ashoka'), x, y: 2 })) }] },
  { id: 'tulsi-court', name: 'Tulsi courtyard', category: 'garden', keywords: ['tulsi', 'vrindavan', 'courtyard', 'pooja', 'vastu', 'angan'], description: 'A terracotta court with a tulsi vrindavan and fragrant jasmine.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 10, d: 10, fits: 'Vrindavan · mogra · diya lamp', parts: [], site: [{ kind: 'patio', name: 'Tulsi court', x: 0, y: 0, w: 10, h: 10, material: 'terracotta-paver' }], props: [{ asset: 'tulsi-vrindavan', x: 5, y: 5 }, { asset: PL('jasmine'), x: 1.4, y: 8.6 }, { asset: PL('jasmine'), x: 8.6, y: 8.6 }, { asset: PL('marigold'), x: 1.2, y: 1.2 }, { asset: PL('marigold'), x: 8.8, y: 1.2 }] }] },
  { id: 'water-garden', name: 'Lotus pond', category: 'garden', keywords: ['pond', 'water garden', 'lotus', 'koi', 'water lily', 'water feature'], description: 'A still pond with lotus and lilies, boulders at the edge and a bench to watch it from.', siteOnly: true,
    sizes: [{ id: 'S', label: 'Small', w: 12, d: 10, fits: '8 × 6 ft pond · water lilies', parts: [], site: [{ kind: 'pond', name: 'Pond', x: 2, y: 2, w: 8, h: 6, material: 'pond-water' }], props: [{ asset: PL('water-lily'), x: 4.5, y: 5 }, { asset: PL('water-lily'), x: 7.6, y: 4.4 }, { asset: PL('canna'), x: 1, y: 8.8 }, { asset: PL('canna'), x: 11, y: 1.2 }] },
      { id: 'M', label: 'Large', w: 18, d: 14, fits: '12 × 8 ft pond · lotus · bench', parts: [], site: [{ kind: 'pond', name: 'Pond', x: 3, y: 4, w: 12, h: 8, material: 'pond-water' }], props: [{ asset: PL('lotus'), x: 6.4, y: 9 }, { asset: PL('lotus'), x: 11.6, y: 7 }, { asset: PL('water-lily'), x: 9, y: 6 }, { asset: PL('water-lily'), x: 13, y: 10 }, { asset: 'boulders', x: 16.2, y: 3.4 }, { asset: PL('canna'), x: 1.4, y: 12.4 }, { asset: PL('canna'), x: 2.2, y: 10.6 }, { asset: PL('fern'), x: 16.6, y: 12.6 }, { asset: 'garden-bench', x: 9, y: 1.6, rot: 180 }] }] },
  { id: 'fountain-court', name: 'Fountain court', category: 'garden', keywords: ['fountain', 'court', 'formal', 'water feature', 'courtyard'], description: 'A cobbled court around a tiered fountain, held at the corners by clipped box.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 16, d: 16, fits: 'Tiered fountain · 4 box balls', parts: [], site: [{ kind: 'patio', name: 'Fountain court', x: 0, y: 0, w: 16, h: 16, material: 'cobble' }], props: [{ asset: 'fountain', x: 8, y: 8 }, { asset: PL('boxwood'), x: 2, y: 2 }, { asset: PL('boxwood'), x: 14, y: 2 }, { asset: PL('boxwood'), x: 2, y: 14 }, { asset: PL('boxwood'), x: 14, y: 14 }] }] },
  { id: 'succulent-garden', name: 'Dry succulent garden', category: 'garden', keywords: ['succulent', 'cactus', 'dry garden', 'xeriscape', 'low water', 'desert', 'rock'], description: 'Agave, yucca and barrel cactus in pebbles — almost no watering.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 14, d: 8, fits: 'Agave · yucca · cactus · boulders', parts: [], site: [{ kind: 'gravel', name: 'Succulent garden', x: 0, y: 0, w: 14, h: 8, material: 'white-pebble' }], props: [{ asset: PL('yucca'), x: 2.6, y: 5.6 }, { asset: PL('agave'), x: 7, y: 4.6 }, { asset: PL('agave'), x: 11.4, y: 2.6 }, { asset: PL('barrel-cactus'), x: 4.4, y: 1.8 }, { asset: PL('barrel-cactus'), x: 6, y: 1.4 }, { asset: PL('barrel-cactus'), x: 5.2, y: 3 }, { asset: PL('aloe'), x: 9.6, y: 6.6 }, { asset: PL('aloe'), x: 1.4, y: 1.6 }, { asset: 'boulders', x: 11.6, y: 6 }] }] },
  { id: 'rose-garden', name: 'Rose garden', category: 'garden', keywords: ['rose', 'roses', 'cottage', 'english garden', 'arch', 'flowers'], description: 'Rose beds either side of a path through a planted arch.', siteOnly: true,
    sizes: [{ id: 'M', label: 'Standard', w: 14, d: 12, fits: '12 roses · arch · bench', parts: [], site: [{ kind: 'bed', name: 'Rose bed', x: 0, y: 0, w: 5, h: 12, material: 'mulch' }, { kind: 'pathway', name: 'Garden path', x: 5, y: 0, w: 4, h: 12, material: 'brick-paver' }, { kind: 'bed', name: 'Rose bed', x: 9, y: 0, w: 5, h: 12, material: 'mulch' }], props: [...[2, 5, 8, 11].flatMap((y) => [{ asset: PL('rose'), x: 1.4, y }, { asset: PL('rose'), x: 3.6, y: y - 1 > 0.6 ? y - 1 : 1 }, { asset: PL('rose'), x: 11.5, y }]), { asset: 'garden-arch', x: 7, y: 1.4 }, { asset: PL('lavender'), x: 9.8, y: 2 }, { asset: PL('lavender'), x: 9.8, y: 6 }, { asset: PL('lavender'), x: 9.8, y: 10 }] }] },
  { id: 'shade-tree-seat', name: 'Shade tree + seat', category: 'garden', keywords: ['shade tree', 'tree', 'neem', 'bench', 'tree seat', 'katta'], description: 'A single spreading tree with a bench beneath and an uplight for the evening.', siteOnly: true,
    sizes: [{ id: 'S', label: 'Frangipani', w: 10, d: 10, fits: 'Frangipani · bench', parts: [], site: [{ kind: 'gravel', name: 'Tree seat', x: 1.5, y: 1.5, w: 7, h: 7, material: 'gravel' }], props: [{ asset: PL('frangipani'), x: 5, y: 5.6 }, { asset: 'garden-bench', x: 5, y: 3, rot: 180 }, { asset: 'uplight', x: 6.4, y: 6.4 }] },
      { id: 'M', label: 'Neem', w: 16, d: 16, fits: 'Neem · two benches', parts: [], site: [{ kind: 'gravel', name: 'Tree seat', x: 3, y: 3, w: 10, h: 10, material: 'gravel' }], props: [{ asset: PL('neem'), x: 8, y: 8 }, { asset: 'garden-bench', x: 8, y: 4.4, rot: 180 }, { asset: 'garden-bench', x: 8, y: 11.6 }, { asset: 'uplight', x: 9.6, y: 9.6 }] }] },
  { id: 'orchard', name: 'Fruit orchard', category: 'garden', keywords: ['orchard', 'fruit', 'mango', 'fruit trees', 'grove'], description: 'Mango, lemon and banana on a grid, far enough apart to crop well.', siteOnly: true,
    sizes: [{ id: 'M', label: '5 trees', w: 30, d: 24, fits: 'Mango · lemon · banana · curry leaf', parts: [], site: [{ kind: 'lawn', name: 'Orchard', x: 0, y: 0, w: 30, h: 24, material: 'lawn' }], props: [{ asset: PL('mango'), x: 8, y: 16 }, { asset: PL('lemon'), x: 22, y: 18 }, { asset: PL('lemon'), x: 22, y: 6 }, { asset: PL('banana'), x: 27, y: 12 }, { asset: PL('curry-leaf'), x: 5, y: 4 }] }] },
];

export const BLOCK_BY_ID: Record<string, BlockDef> = Object.fromEntries(BLOCKS.map((b) => [b.id, b]));

export function blockSize(def: BlockDef, sizeId?: string): BlockSize {
  return def.sizes.find((s) => s.id === sizeId) ?? def.sizes[Math.min(1, def.sizes.length - 1)];
}

/** Search blocks by plain words ("attached bathroom", "pooja", "2bhk"). */
export function searchBlocks(q: string): BlockDef[] {
  const t = q.trim().toLowerCase();
  if (!t) return BLOCKS;
  const STOP = new Set(['a', 'an', 'the', 'for', 'with', 'and', 'of', 'to', 'my', 'in', 'on', 'room', 'space']);
  const words = t.split(/[\s,]+/).filter((w) => w && !STOP.has(w) && !/^\d+$/.test(w)).map((w) => w.replace(/s$/, ''));
  return BLOCKS.map((b) => {
    const key = `${b.name} ${b.keywords.join(' ')}`.toLowerCase();
    const desc = b.description.toLowerCase();
    // Name and keyword hits count double; descriptions only break ties.
    const score = words.reduce((s, w) => s + (key.includes(w) ? 2 : desc.includes(w) ? 0.5 : 0), 0) + (b.name.toLowerCase().includes(t) ? 3 : 0) + (b.name.toLowerCase().startsWith(t) ? 1 : 0);
    return { b, score };
  }).filter((x) => x.score >= 1).sort((a, b) => b.score - a.score).map((x) => x.b);
}
