/**
 * Plant library. Every plant carries the horticultural facts a landscape
 * drawing needs — botanical name, mature size, sun and water demand, planting
 * distance — and a growth form that drives both its plan symbol and its
 * procedural 3D model. Sizes are mature garden sizes in millimetres.
 */

export type PlantType = 'tree' | 'palm' | 'shrub' | 'bamboo' | 'grass' | 'flower' | 'groundcover' | 'succulent' | 'tropical' | 'climber' | 'aquatic';

/** Growth habit: the silhouette the 3D generator and the plan symbol draw. */
export type PlantForm =
  | 'canopy' | 'umbrella' | 'weeping' | 'columnar' | 'conifer'
  | 'palm' | 'fanpalm' | 'clumppalm' | 'bamboo'
  | 'shrub' | 'topiary' | 'grass' | 'flower' | 'groundcover'
  | 'rosette' | 'paddle' | 'climber' | 'aquatic';

export type Sun = 'full' | 'partial' | 'shade';
export type Water = 'low' | 'medium' | 'high';
export type Climate = 'tropical' | 'subtropical' | 'arid' | 'mediterranean' | 'temperate';
export type LandscapeStyle = 'tropical' | 'modern' | 'mediterranean' | 'zen' | 'indian' | 'cottage';

export interface Plant {
  id: string;
  common: string;
  botanical: string;
  type: PlantType;
  form: PlantForm;
  /** Mature height and spread, mm. */
  height: number;
  spread: number;
  sun: Sun;
  water: Water;
  evergreen: boolean;
  foliage: string;
  /** Second foliage tone (variegation, new growth, autumn colour). */
  foliage2?: string;
  bark?: string;
  flower?: { color: string; season: string };
  climates: Climate[];
  styles: LandscapeStyle[];
  /** Recommended planting distance centre to centre, mm. */
  spacing: number;
  /** Supply + planting at nursery size, INR. */
  price: number;
  /** Something worth knowing before specifying it. */
  note: string;
  /** Sold and shown in a pot — usable on terraces and balconies. */
  potted?: boolean;
}

const P = (p: Plant) => p;
const ALL: Climate[] = ['tropical', 'subtropical'];
const WARM: Climate[] = ['tropical', 'subtropical', 'arid'];
const MED: Climate[] = ['mediterranean', 'subtropical', 'arid', 'temperate'];
const TEMP: Climate[] = ['temperate', 'mediterranean', 'subtropical'];

export const PLANTS: Plant[] = [
  // ------------------------------------------------------------------ trees
  P({ id: 'neem', common: 'Neem', botanical: 'Azadirachta indica', type: 'tree', form: 'canopy', height: 12000, spread: 9000, sun: 'full', water: 'low', evergreen: true, foliage: '#5c8a3c', foliage2: '#7aa550', bark: '#5d4a3a', flower: { color: '#f3f0dc', season: 'Mar–May' }, climates: WARM, styles: ['indian', 'tropical'], spacing: 8000, price: 4500, note: 'Dense shade, purifies air; keep 5 m from foundations.' }),
  P({ id: 'mango', common: 'Mango', botanical: 'Mangifera indica', type: 'tree', form: 'canopy', height: 10000, spread: 9000, sun: 'full', water: 'medium', evergreen: true, foliage: '#3f6e33', foliage2: '#8a5a3a', bark: '#4f4034', flower: { color: '#e6d9a8', season: 'Feb–Mar' }, climates: ALL, styles: ['indian', 'tropical'], spacing: 9000, price: 6500, note: 'Fruits May–July; coppery new leaves. Needs space.' }),
  P({ id: 'gulmohar', common: 'Gulmohar (flame tree)', botanical: 'Delonix regia', type: 'tree', form: 'umbrella', height: 10000, spread: 12000, sun: 'full', water: 'low', evergreen: false, foliage: '#6a9a45', bark: '#8a7a68', flower: { color: '#d9381e', season: 'Apr–Jun' }, climates: WARM, styles: ['indian', 'tropical'], spacing: 10000, price: 5500, note: 'Spectacular scarlet canopy; brittle branches and surface roots.' }),
  P({ id: 'jacaranda', common: 'Jacaranda', botanical: 'Jacaranda mimosifolia', type: 'tree', form: 'canopy', height: 10000, spread: 8000, sun: 'full', water: 'medium', evergreen: false, foliage: '#6f9d55', bark: '#6b5a48', flower: { color: '#8a6fc9', season: 'Mar–May' }, climates: ['subtropical', 'mediterranean', 'tropical'], styles: ['mediterranean', 'cottage', 'modern'], spacing: 8000, price: 7000, note: 'Lilac bloom before the leaves; carpets paving with petals.' }),
  P({ id: 'frangipani', common: 'Frangipani (champa)', botanical: 'Plumeria rubra', type: 'tree', form: 'umbrella', height: 5000, spread: 4500, sun: 'full', water: 'low', evergreen: false, foliage: '#4f8a3f', bark: '#9a9186', flower: { color: '#fbf3d5', season: 'Mar–Oct' }, climates: WARM, styles: ['tropical', 'modern', 'indian', 'zen'], spacing: 4500, price: 9000, note: 'Sculptural branches and fragrant flowers; ideal courtyard tree.' }),
  P({ id: 'rain-tree', common: 'Rain tree', botanical: 'Samanea saman', type: 'tree', form: 'umbrella', height: 15000, spread: 18000, sun: 'full', water: 'medium', evergreen: true, foliage: '#4d7d39', bark: '#4a3d33', flower: { color: '#e8a6c0', season: 'Mar–Sep' }, climates: ALL, styles: ['tropical', 'indian'], spacing: 15000, price: 8000, note: 'Very wide canopy — for large plots and estate avenues only.' }),
  P({ id: 'ashoka', common: 'Ashoka (mast tree)', botanical: 'Monoon longifolium', type: 'tree', form: 'columnar', height: 10000, spread: 1800, sun: 'full', water: 'medium', evergreen: true, foliage: '#3d6b35', bark: '#55483c', climates: ALL, styles: ['indian', 'modern', 'tropical'], spacing: 1800, price: 2200, note: 'Narrow evergreen screen for boundaries; blocks noise and views.' }),
  P({ id: 'amaltas', common: 'Amaltas (golden shower)', botanical: 'Cassia fistula', type: 'tree', form: 'weeping', height: 9000, spread: 6000, sun: 'full', water: 'low', evergreen: false, foliage: '#6b9a4a', bark: '#7a6a58', flower: { color: '#f2c230', season: 'Apr–Jun' }, climates: WARM, styles: ['indian', 'tropical', 'cottage'], spacing: 6000, price: 4800, note: 'Hanging yellow racemes in summer; drought tolerant.' }),
  P({ id: 'ficus', common: 'Weeping fig', botanical: 'Ficus benjamina', type: 'tree', form: 'canopy', height: 8000, spread: 6000, sun: 'partial', water: 'medium', evergreen: true, foliage: '#3f7038', foliage2: '#5e9148', bark: '#8f8a80', climates: ALL, styles: ['modern', 'tropical'], spacing: 5000, price: 5200, note: 'Glossy dense crown; aggressive roots — keep clear of drains.' }),
  P({ id: 'olive', common: 'Olive', botanical: 'Olea europaea', type: 'tree', form: 'canopy', height: 6000, spread: 5000, sun: 'full', water: 'low', evergreen: true, foliage: '#8a9a78', foliage2: '#b6c0a6', bark: '#6f675c', climates: MED, styles: ['mediterranean', 'modern'], spacing: 5000, price: 28000, note: 'Silver foliage and gnarled trunk; needs sharp drainage.' }),
  P({ id: 'cypress', common: 'Italian cypress', botanical: 'Cupressus sempervirens', type: 'tree', form: 'columnar', height: 12000, spread: 1500, sun: 'full', water: 'low', evergreen: true, foliage: '#2f5236', bark: '#5a4c40', climates: MED, styles: ['mediterranean', 'modern'], spacing: 1500, price: 6500, note: 'Formal vertical accent for drives and entrances.' }),
  P({ id: 'maple', common: 'Japanese maple', botanical: 'Acer palmatum', type: 'tree', form: 'umbrella', height: 4000, spread: 4000, sun: 'partial', water: 'medium', evergreen: false, foliage: '#a23b2a', foliage2: '#c9612f', bark: '#5c4a40', climates: ['temperate'], styles: ['zen', 'cottage', 'modern'], spacing: 4000, price: 32000, note: 'Layered crimson foliage; needs shelter from hot afternoon sun.' }),
  P({ id: 'bottlebrush', common: 'Bottlebrush', botanical: 'Callistemon viminalis', type: 'tree', form: 'weeping', height: 5000, spread: 3500, sun: 'full', water: 'low', evergreen: true, foliage: '#5a8548', bark: '#6a5a4a', flower: { color: '#c8262c', season: 'Mar–Jun' }, climates: ['subtropical', 'tropical', 'mediterranean'], styles: ['cottage', 'tropical', 'modern'], spacing: 3500, price: 3200, note: 'Weeping habit with red brushes; draws sunbirds and bees.' }),
  P({ id: 'tabebuia', common: 'Pink trumpet tree', botanical: 'Tabebuia rosea', type: 'tree', form: 'canopy', height: 9000, spread: 7000, sun: 'full', water: 'medium', evergreen: false, foliage: '#5d8f45', bark: '#77695a', flower: { color: '#e58fb0', season: 'Feb–Apr' }, climates: ALL, styles: ['tropical', 'indian', 'cottage'], spacing: 7000, price: 5200, note: 'Blossoms on bare branches in spring; fast growing.' }),
  P({ id: 'champaca', common: 'Son champa', botanical: 'Magnolia champaca', type: 'tree', form: 'canopy', height: 9000, spread: 5000, sun: 'full', water: 'medium', evergreen: true, foliage: '#4a7f3c', bark: '#6c6156', flower: { color: '#f0b93a', season: 'Jun–Sep' }, climates: ALL, styles: ['indian', 'tropical'], spacing: 5000, price: 4200, note: 'Intensely fragrant golden flowers; a traditional temple tree.' }),
  P({ id: 'lemon', common: 'Lemon', botanical: 'Citrus × limon', type: 'tree', form: 'canopy', height: 3500, spread: 3000, sun: 'full', water: 'medium', evergreen: true, foliage: '#3f7a36', bark: '#6a5d4d', flower: { color: '#f4d23c', season: 'Year-round' }, climates: ['subtropical', 'mediterranean', 'tropical'], styles: ['mediterranean', 'indian', 'cottage'], spacing: 3000, price: 1800, note: 'Compact fruiting tree for kitchen gardens and large pots.' }),
  P({ id: 'curry-leaf', common: 'Curry leaf', botanical: 'Murraya koenigii', type: 'tree', form: 'canopy', height: 4000, spread: 2500, sun: 'full', water: 'medium', evergreen: true, foliage: '#3c7436', bark: '#5f5246', climates: ALL, styles: ['indian'], spacing: 2500, price: 900, note: 'Kitchen-garden staple; harvest leaves year-round.' }),
  P({ id: 'araucaria', common: 'Christmas tree', botanical: 'Araucaria columnaris', type: 'tree', form: 'conifer', height: 15000, spread: 4000, sun: 'full', water: 'medium', evergreen: true, foliage: '#2f5d3a', bark: '#5a4a3e', climates: ALL, styles: ['modern', 'tropical'], spacing: 4000, price: 6800, note: 'Symmetrical tiers; a strong vertical marker for an entrance.' }),
  P({ id: 'kachnar', common: 'Kachnar (orchid tree)', botanical: 'Bauhinia variegata', type: 'tree', form: 'canopy', height: 8000, spread: 6000, sun: 'full', water: 'low', evergreen: false, foliage: '#699a4c', bark: '#6d6052', flower: { color: '#d782b4', season: 'Feb–Apr' }, climates: WARM, styles: ['indian', 'cottage', 'tropical'], spacing: 6000, price: 3600, note: 'Orchid-like blooms; light canopy suits small gardens.' }),
  P({ id: 'crepe-myrtle', common: 'Crepe myrtle', botanical: 'Lagerstroemia indica', type: 'tree', form: 'umbrella', height: 5000, spread: 4000, sun: 'full', water: 'medium', evergreen: false, foliage: '#5f9247', foliage2: '#c9652f', bark: '#b7a48f', flower: { color: '#d55f9a', season: 'May–Sep' }, climates: ['subtropical', 'temperate', 'mediterranean', 'tropical'], styles: ['cottage', 'modern', 'mediterranean'], spacing: 4000, price: 4500, note: 'Long summer bloom and peeling bark; good small street tree.' }),
  P({ id: 'banana', common: 'Banana', botanical: 'Musa × paradisiaca', type: 'tropical', form: 'paddle', height: 4000, spread: 3000, sun: 'full', water: 'high', evergreen: true, foliage: '#5a9a3e', foliage2: '#86bd55', bark: '#8aa05a', climates: ALL, styles: ['tropical', 'indian'], spacing: 2500, price: 600, note: 'Fast lush screen; considered auspicious at entrances.' }),
  // ------------------------------------------------------------------ palms
  P({ id: 'coconut', common: 'Coconut palm', botanical: 'Cocos nucifera', type: 'palm', form: 'palm', height: 15000, spread: 6000, sun: 'full', water: 'high', evergreen: true, foliage: '#4f8a3a', foliage2: '#79a84c', bark: '#8a7c6a', climates: ['tropical'], styles: ['tropical', 'indian'], spacing: 7500, price: 3500, note: 'Coastal icon; keep clear of roofs, parking and play areas (falling nuts).' }),
  P({ id: 'royal-palm', common: 'Royal palm', botanical: 'Roystonea regia', type: 'palm', form: 'palm', height: 15000, spread: 5000, sun: 'full', water: 'medium', evergreen: true, foliage: '#467f37', bark: '#b3ada2', climates: ALL, styles: ['tropical', 'modern', 'mediterranean'], spacing: 5000, price: 14000, note: 'Smooth grey column — the classic avenue palm for grand drives.' }),
  P({ id: 'areca', common: 'Areca palm', botanical: 'Dypsis lutescens', type: 'palm', form: 'clumppalm', height: 5000, spread: 3000, sun: 'partial', water: 'medium', evergreen: true, foliage: '#5d9a44', foliage2: '#b9c45a', bark: '#b5a85a', climates: ALL, styles: ['tropical', 'modern', 'indian'], spacing: 1800, price: 1800, note: 'Soft clumping screen; equally good in pots indoors.', potted: true }),
  P({ id: 'foxtail', common: 'Foxtail palm', botanical: 'Wodyetia bifurcata', type: 'palm', form: 'palm', height: 9000, spread: 4000, sun: 'full', water: 'medium', evergreen: true, foliage: '#4a8a3c', bark: '#a39c90', climates: ALL, styles: ['tropical', 'modern'], spacing: 3500, price: 8500, note: 'Plume-like fronds, self-cleaning — low maintenance by pools.' }),
  P({ id: 'bismarck', common: 'Bismarck palm', botanical: 'Bismarckia nobilis', type: 'palm', form: 'fanpalm', height: 9000, spread: 6000, sun: 'full', water: 'low', evergreen: true, foliage: '#8fa39a', foliage2: '#b4c2ba', bark: '#7a6f62', climates: WARM, styles: ['modern', 'mediterranean', 'tropical'], spacing: 6000, price: 22000, note: 'Huge silver-blue fans; a single specimen anchors a lawn.' }),
  P({ id: 'pygmy-date', common: 'Pygmy date palm', botanical: 'Phoenix roebelenii', type: 'palm', form: 'palm', height: 2500, spread: 2000, sun: 'partial', water: 'medium', evergreen: true, foliage: '#4c8540', bark: '#6f6254', climates: ALL, styles: ['tropical', 'modern', 'mediterranean'], spacing: 2000, price: 4800, note: 'Small-scale palm for courtyards, pool edges and pots.', potted: true }),
  P({ id: 'travellers', common: 'Traveller’s palm', botanical: 'Ravenala madagascariensis', type: 'tropical', form: 'paddle', height: 8000, spread: 5000, sun: 'full', water: 'high', evergreen: true, foliage: '#4f9240', foliage2: '#7db55a', bark: '#8b7f6c', climates: ['tropical'], styles: ['tropical', 'modern'], spacing: 4000, price: 5500, note: 'Flat fan of banana-like leaves; dramatic against a plain wall.' }),
  P({ id: 'cycas', common: 'Sago palm', botanical: 'Cycas revoluta', type: 'palm', form: 'rosette', height: 1500, spread: 1800, sun: 'partial', water: 'low', evergreen: true, foliage: '#2f6a39', bark: '#5c4e42', climates: ['subtropical', 'tropical', 'mediterranean'], styles: ['zen', 'modern', 'tropical'], spacing: 1800, price: 6500, note: 'Slow, architectural rosette; toxic to pets if chewed.', potted: true }),
  // ------------------------------------------------------- bamboo & grasses
  P({ id: 'bamboo', common: 'Golden bamboo', botanical: 'Bambusa vulgaris ‘Vittata’', type: 'bamboo', form: 'bamboo', height: 8000, spread: 3000, sun: 'full', water: 'high', evergreen: true, foliage: '#6fa348', bark: '#c9b24a', climates: ALL, styles: ['zen', 'tropical', 'modern'], spacing: 2500, price: 2200, note: 'Fast privacy screen; clumping — install a root barrier near paving.' }),
  P({ id: 'fountain-grass', common: 'Purple fountain grass', botanical: 'Pennisetum × advena ‘Rubrum’', type: 'grass', form: 'grass', height: 1200, spread: 900, sun: 'full', water: 'low', evergreen: true, foliage: '#7a3f4a', foliage2: '#b98a8f', climates: ['subtropical', 'tropical', 'mediterranean', 'arid'], styles: ['modern', 'mediterranean', 'cottage'], spacing: 700, price: 220, note: 'Burgundy blades and arching plumes; mass for movement.' }),
  P({ id: 'lemongrass', common: 'Lemongrass', botanical: 'Cymbopogon citratus', type: 'grass', form: 'grass', height: 1200, spread: 900, sun: 'full', water: 'medium', evergreen: true, foliage: '#8fb357', climates: ALL, styles: ['indian', 'tropical', 'modern'], spacing: 700, price: 120, note: 'Edible, mosquito-deterring edging for sit-outs.' }),
  P({ id: 'pampas', common: 'Pampas grass', botanical: 'Cortaderia selloana', type: 'grass', form: 'grass', height: 2500, spread: 2000, sun: 'full', water: 'low', evergreen: true, foliage: '#8aa56a', foliage2: '#efe6cf', climates: MED, styles: ['modern', 'mediterranean'], spacing: 1800, price: 650, note: 'Tall cream plumes; sharp leaves — keep off paths.' }),
  P({ id: 'mondo', common: 'Mondo grass', botanical: 'Ophiopogon japonicus', type: 'groundcover', form: 'groundcover', height: 200, spread: 300, sun: 'shade', water: 'medium', evergreen: true, foliage: '#2f5f36', climates: ['subtropical', 'temperate', 'tropical'], styles: ['zen', 'modern'], spacing: 150, price: 35, note: 'Dark tufts between stepping stones; tolerates deep shade.' }),
  // ------------------------------------------------------ shrubs and hedges
  P({ id: 'hibiscus', common: 'Hibiscus', botanical: 'Hibiscus rosa-sinensis', type: 'shrub', form: 'shrub', height: 2500, spread: 2000, sun: 'full', water: 'medium', evergreen: true, foliage: '#3f7a38', flower: { color: '#d7263d', season: 'Year-round' }, climates: ALL, styles: ['tropical', 'indian', 'cottage'], spacing: 1200, price: 350, note: 'Flowers daily; used for worship. Prune hard after monsoon.' }),
  P({ id: 'bougainvillea', common: 'Bougainvillea', botanical: 'Bougainvillea glabra', type: 'climber', form: 'climber', height: 3000, spread: 3000, sun: 'full', water: 'low', evergreen: true, foliage: '#4c8a3f', flower: { color: '#d6247f', season: 'Oct–May' }, climates: WARM.concat('mediterranean'), styles: ['mediterranean', 'tropical', 'indian'], spacing: 2000, price: 450, note: 'Blazes when kept dry; thorny — train over walls and pergolas.' }),
  P({ id: 'ixora', common: 'Ixora', botanical: 'Ixora coccinea', type: 'shrub', form: 'shrub', height: 1200, spread: 1000, sun: 'full', water: 'medium', evergreen: true, foliage: '#356e33', flower: { color: '#e2472c', season: 'Year-round' }, climates: ALL, styles: ['tropical', 'indian'], spacing: 600, price: 180, note: 'Neat flowering low hedge; needs acidic soil.' }),
  P({ id: 'croton', common: 'Croton', botanical: 'Codiaeum variegatum', type: 'shrub', form: 'shrub', height: 1500, spread: 1000, sun: 'partial', water: 'medium', evergreen: true, foliage: '#5a8a35', foliage2: '#e0a52c', climates: ALL, styles: ['tropical', 'indian'], spacing: 700, price: 220, note: 'Painted foliage in yellow, red and green; colour fades in deep shade.', potted: true }),
  P({ id: 'boxwood', common: 'Boxwood ball', botanical: 'Buxus sempervirens', type: 'shrub', form: 'topiary', height: 900, spread: 900, sun: 'partial', water: 'medium', evergreen: true, foliage: '#3c6f3a', climates: TEMP, styles: ['modern', 'cottage', 'mediterranean'], spacing: 900, price: 3800, note: 'Clipped sphere for formal rhythm; shear twice a year.', potted: true }),
  P({ id: 'duranta', common: 'Golden duranta', botanical: 'Duranta erecta ‘Gold Mound’', type: 'shrub', form: 'shrub', height: 800, spread: 800, sun: 'full', water: 'medium', evergreen: true, foliage: '#b8c93f', foliage2: '#d9de6a', climates: ALL, styles: ['modern', 'tropical', 'indian'], spacing: 300, price: 40, note: 'Lime-gold low hedge that contrasts with dark greens.' }),
  P({ id: 'murraya', common: 'Kamini (orange jasmine)', botanical: 'Murraya paniculata', type: 'shrub', form: 'shrub', height: 3000, spread: 2000, sun: 'full', water: 'medium', evergreen: true, foliage: '#2f6a34', flower: { color: '#fbfaf0', season: 'Mar–Sep' }, climates: ALL, styles: ['indian', 'modern', 'tropical', 'mediterranean'], spacing: 500, price: 160, note: 'The best clipped hedge for warm climates; citrus-scented bloom.' }),
  P({ id: 'jasmine', common: 'Mogra (Arabian jasmine)', botanical: 'Jasminum sambac', type: 'shrub', form: 'shrub', height: 1500, spread: 1200, sun: 'full', water: 'medium', evergreen: true, foliage: '#3d7a3a', flower: { color: '#ffffff', season: 'Mar–Sep' }, climates: ALL, styles: ['indian', 'cottage', 'tropical'], spacing: 800, price: 180, note: 'Evening fragrance — plant by bedrooms and sit-outs.', potted: true }),
  P({ id: 'oleander', common: 'Kaner (oleander)', botanical: 'Nerium oleander', type: 'shrub', form: 'shrub', height: 3000, spread: 2500, sun: 'full', water: 'low', evergreen: true, foliage: '#587f52', flower: { color: '#e889a8', season: 'Mar–Oct' }, climates: WARM.concat('mediterranean'), styles: ['mediterranean', 'indian'], spacing: 1500, price: 220, note: 'Tough roadside screen. All parts are poisonous — avoid near play areas.' }),
  P({ id: 'plumbago', common: 'Plumbago', botanical: 'Plumbago auriculata', type: 'shrub', form: 'shrub', height: 1500, spread: 1500, sun: 'full', water: 'low', evergreen: true, foliage: '#5f9150', flower: { color: '#8db8e8', season: 'Mar–Nov' }, climates: ['subtropical', 'mediterranean', 'tropical'], styles: ['cottage', 'mediterranean'], spacing: 900, price: 160, note: 'Sky-blue clouds of flower; scrambles over low walls.' }),
  P({ id: 'tecoma', common: 'Yellow bells', botanical: 'Tecoma stans', type: 'shrub', form: 'shrub', height: 4000, spread: 3000, sun: 'full', water: 'low', evergreen: true, foliage: '#5c9445', flower: { color: '#f4cb2e', season: 'Year-round' }, climates: WARM, styles: ['indian', 'cottage', 'tropical'], spacing: 2000, price: 250, note: 'Quick, cheerful screen; seeds freely.' }),
  P({ id: 'rose', common: 'Rose', botanical: 'Rosa × hybrida', type: 'shrub', form: 'flower', height: 1200, spread: 900, sun: 'full', water: 'medium', evergreen: false, foliage: '#3f7438', flower: { color: '#c8344a', season: 'Oct–Mar' }, climates: TEMP.concat('subtropical'), styles: ['cottage', 'indian', 'mediterranean'], spacing: 700, price: 280, note: 'Six hours of sun and good air flow; feed monthly in season.' }),
  P({ id: 'lavender', common: 'Lavender', botanical: 'Lavandula angustifolia', type: 'shrub', form: 'flower', height: 600, spread: 700, sun: 'full', water: 'low', evergreen: true, foliage: '#8a9a8a', flower: { color: '#8a72c2', season: 'May–Aug' }, climates: ['mediterranean', 'temperate'], styles: ['mediterranean', 'cottage', 'modern'], spacing: 450, price: 320, note: 'Needs dry heat and lean soil; fails in humid monsoon climates.' }),
  P({ id: 'rosemary', common: 'Rosemary', botanical: 'Salvia rosmarinus', type: 'shrub', form: 'shrub', height: 1000, spread: 900, sun: 'full', water: 'low', evergreen: true, foliage: '#5d7a5e', flower: { color: '#9aa9d8', season: 'Feb–May' }, climates: ['mediterranean', 'temperate', 'arid'], styles: ['mediterranean', 'cottage'], spacing: 600, price: 260, note: 'Aromatic kitchen herb and clipped low hedge.', potted: true }),
  P({ id: 'tulsi', common: 'Tulsi (holy basil)', botanical: 'Ocimum tenuiflorum', type: 'shrub', form: 'shrub', height: 600, spread: 400, sun: 'full', water: 'medium', evergreen: true, foliage: '#4f8a44', flower: { color: '#a779b8', season: 'Year-round' }, climates: ALL, styles: ['indian'], spacing: 400, price: 60, note: 'Traditionally kept in a vrindavan at the north-east or centre of the courtyard.', potted: true }),
  P({ id: 'hydrangea', common: 'Hydrangea', botanical: 'Hydrangea macrophylla', type: 'shrub', form: 'flower', height: 1200, spread: 1200, sun: 'partial', water: 'high', evergreen: false, foliage: '#4a8242', flower: { color: '#7fa3dc', season: 'May–Sep' }, climates: ['temperate'], styles: ['cottage', 'zen'], spacing: 1000, price: 650, note: 'Mophead blooms; blue on acid soil, pink on alkaline.' }),
  P({ id: 'azalea', common: 'Azalea', botanical: 'Rhododendron simsii', type: 'shrub', form: 'flower', height: 1000, spread: 1000, sun: 'partial', water: 'medium', evergreen: true, foliage: '#3d7139', flower: { color: '#e05a8c', season: 'Feb–Apr' }, climates: ['temperate', 'subtropical'], styles: ['zen', 'cottage'], spacing: 800, price: 480, note: 'Cloud-pruned in Japanese gardens; acid soil only.' }),
  // --------------------------------------------------------- tropical foliage
  P({ id: 'bird-of-paradise', common: 'Bird of paradise', botanical: 'Strelitzia reginae', type: 'tropical', form: 'paddle', height: 1500, spread: 1200, sun: 'full', water: 'medium', evergreen: true, foliage: '#4a7f5a', flower: { color: '#f08a1c', season: 'Sep–May' }, climates: ['subtropical', 'tropical', 'mediterranean'], styles: ['tropical', 'modern', 'mediterranean'], spacing: 1000, price: 950, note: 'Crane-like orange flowers above grey-green paddles.', potted: true }),
  P({ id: 'giant-strelitzia', common: 'Giant white bird of paradise', botanical: 'Strelitzia nicolai', type: 'tropical', form: 'paddle', height: 5000, spread: 3000, sun: 'full', water: 'medium', evergreen: true, foliage: '#3f7a48', climates: ['subtropical', 'tropical', 'mediterranean'], styles: ['tropical', 'modern'], spacing: 2500, price: 4200, note: 'Banana-like scale without the mess; superb beside glass.' }),
  P({ id: 'heliconia', common: 'Heliconia', botanical: 'Heliconia rostrata', type: 'tropical', form: 'paddle', height: 2500, spread: 1500, sun: 'partial', water: 'high', evergreen: true, foliage: '#4c9240', flower: { color: '#e23b2e', season: 'May–Nov' }, climates: ['tropical'], styles: ['tropical'], spacing: 1000, price: 380, note: 'Hanging lobster-claw bracts; spreads into a dense clump.' }),
  P({ id: 'monstera', common: 'Monstera', botanical: 'Monstera deliciosa', type: 'tropical', form: 'paddle', height: 1500, spread: 1500, sun: 'shade', water: 'medium', evergreen: true, foliage: '#2f6f3b', climates: ALL, styles: ['tropical', 'modern'], spacing: 1200, price: 750, note: 'Split leaves for shaded courtyards and covered sit-outs.', potted: true }),
  P({ id: 'philodendron', common: 'Philodendron xanadu', botanical: 'Thaumatophyllum xanadu', type: 'tropical', form: 'rosette', height: 900, spread: 1200, sun: 'shade', water: 'medium', evergreen: true, foliage: '#357a3c', climates: ALL, styles: ['tropical', 'modern'], spacing: 800, price: 420, note: 'Tidy mound of lobed leaves; excellent mass under trees.' }),
  P({ id: 'canna', common: 'Canna lily', botanical: 'Canna indica', type: 'flower', form: 'paddle', height: 1500, spread: 800, sun: 'full', water: 'high', evergreen: true, foliage: '#4f8f3f', foliage2: '#7a3f35', flower: { color: '#ef5a2a', season: 'Year-round' }, climates: ALL, styles: ['tropical', 'indian', 'cottage'], spacing: 500, price: 90, note: 'Bold colour for wet spots and pond margins.' }),
  P({ id: 'spider-lily', common: 'Spider lily', botanical: 'Hymenocallis littoralis', type: 'groundcover', form: 'rosette', height: 700, spread: 700, sun: 'full', water: 'medium', evergreen: true, foliage: '#3f8440', flower: { color: '#ffffff', season: 'Jun–Oct' }, climates: ALL, styles: ['tropical', 'modern', 'indian'], spacing: 400, price: 45, note: 'Strappy edging that survives heat, salt and neglect.' }),
  P({ id: 'fern', common: 'Boston fern', botanical: 'Nephrolepis exaltata', type: 'groundcover', form: 'rosette', height: 600, spread: 900, sun: 'shade', water: 'high', evergreen: true, foliage: '#4f9a48', climates: ALL, styles: ['tropical', 'zen', 'cottage'], spacing: 500, price: 150, note: 'Arching fronds for damp shade and hanging baskets.', potted: true }),
  P({ id: 'alocasia', common: 'Elephant ear', botanical: 'Alocasia macrorrhizos', type: 'tropical', form: 'paddle', height: 2000, spread: 1500, sun: 'partial', water: 'high', evergreen: true, foliage: '#3a7f3f', climates: ['tropical'], styles: ['tropical'], spacing: 1200, price: 550, note: 'Giant upright leaves; jungle scale in a small bed.' }),
  // ------------------------------------------------------- succulents / arid
  P({ id: 'agave', common: 'Century plant', botanical: 'Agave americana', type: 'succulent', form: 'rosette', height: 1500, spread: 2000, sun: 'full', water: 'low', evergreen: true, foliage: '#7f9a94', foliage2: '#a9bdb5', climates: ['arid', 'mediterranean', 'subtropical'], styles: ['modern', 'mediterranean'], spacing: 2000, price: 1800, note: 'Sculptural blue rosette with terminal spines — site away from paths.' }),
  P({ id: 'aloe', common: 'Aloe vera', botanical: 'Aloe vera', type: 'succulent', form: 'rosette', height: 600, spread: 600, sun: 'full', water: 'low', evergreen: true, foliage: '#6f9a72', flower: { color: '#e8a53a', season: 'Dec–Mar' }, climates: WARM.concat('mediterranean'), styles: ['modern', 'indian', 'mediterranean'], spacing: 500, price: 120, note: 'Medicinal and nearly indestructible; needs no irrigation once established.', potted: true }),
  P({ id: 'snake-plant', common: 'Snake plant', botanical: 'Dracaena trifasciata', type: 'succulent', form: 'grass', height: 900, spread: 500, sun: 'shade', water: 'low', evergreen: true, foliage: '#3f6b47', foliage2: '#c9c36a', climates: ALL, styles: ['modern', 'zen'], spacing: 350, price: 250, note: 'Upright blades for narrow planters and low-light corners.', potted: true }),
  P({ id: 'yucca', common: 'Spineless yucca', botanical: 'Yucca gigantea', type: 'succulent', form: 'rosette', height: 4000, spread: 2000, sun: 'full', water: 'low', evergreen: true, foliage: '#4f7f4a', bark: '#8a7a68', climates: ['arid', 'mediterranean', 'subtropical'], styles: ['modern', 'mediterranean'], spacing: 1800, price: 3200, note: 'Trunk-forming sword leaves; strong modern silhouette.', potted: true }),
  P({ id: 'barrel-cactus', common: 'Golden barrel cactus', botanical: 'Echinocactus grusonii', type: 'succulent', form: 'topiary', height: 600, spread: 600, sun: 'full', water: 'low', evergreen: true, foliage: '#7a9a4a', foliage2: '#d9c95a', climates: ['arid', 'mediterranean'], styles: ['modern', 'mediterranean'], spacing: 700, price: 2400, note: 'Spheres in gravel — repeat in odd-numbered groups.' }),
  // ---------------------------------------------- flowers and ground covers
  P({ id: 'marigold', common: 'Marigold', botanical: 'Tagetes erecta', type: 'flower', form: 'flower', height: 500, spread: 400, sun: 'full', water: 'medium', evergreen: false, foliage: '#4a8a3c', flower: { color: '#f29a1f', season: 'Oct–Mar' }, climates: ALL.concat('temperate'), styles: ['indian', 'cottage'], spacing: 300, price: 15, note: 'Seasonal colour; deters nematodes in kitchen beds.' }),
  P({ id: 'vinca', common: 'Sadabahar (periwinkle)', botanical: 'Catharanthus roseus', type: 'flower', form: 'flower', height: 500, spread: 500, sun: 'full', water: 'low', evergreen: true, foliage: '#3f7f3c', flower: { color: '#e06aa6', season: 'Year-round' }, climates: ALL, styles: ['indian', 'cottage', 'tropical'], spacing: 300, price: 20, note: 'Flowers through summer heat with almost no care.' }),
  P({ id: 'petunia', common: 'Petunia', botanical: 'Petunia × atkinsiana', type: 'flower', form: 'flower', height: 350, spread: 500, sun: 'full', water: 'medium', evergreen: false, foliage: '#4f8f42', flower: { color: '#9a4fc2', season: 'Nov–Mar' }, climates: TEMP, styles: ['cottage'], spacing: 300, price: 20, note: 'Winter annual for borders, pots and hanging baskets.', potted: true }),
  P({ id: 'wedelia', common: 'Wedelia', botanical: 'Sphagneticola trilobata', type: 'groundcover', form: 'groundcover', height: 300, spread: 800, sun: 'full', water: 'medium', evergreen: true, foliage: '#3f8a3c', flower: { color: '#f2c81f', season: 'Year-round' }, climates: ALL, styles: ['tropical', 'indian'], spacing: 300, price: 12, note: 'Rapid slope cover; contain it — it runs.' }),
  P({ id: 'rhoeo', common: 'Rhoeo (boat lily)', botanical: 'Tradescantia spathacea', type: 'groundcover', form: 'groundcover', height: 300, spread: 400, sun: 'partial', water: 'low', evergreen: true, foliage: '#5a6f4a', foliage2: '#7a3f6a', climates: ALL, styles: ['modern', 'tropical'], spacing: 250, price: 18, note: 'Purple-backed rosettes for bold contrast edging.' }),
  // ----------------------------------------------------- climbers & aquatic
  P({ id: 'madhumalti', common: 'Madhumalti (Rangoon creeper)', botanical: 'Combretum indicum', type: 'climber', form: 'climber', height: 4000, spread: 3000, sun: 'full', water: 'medium', evergreen: true, foliage: '#4a8a40', flower: { color: '#e4567a', season: 'Mar–Nov' }, climates: ALL, styles: ['indian', 'cottage', 'tropical'], spacing: 2500, price: 280, note: 'Flowers open white and turn red; perfumes a pergola at dusk.' }),
  P({ id: 'star-jasmine', common: 'Star jasmine', botanical: 'Trachelospermum jasminoides', type: 'climber', form: 'climber', height: 4000, spread: 2500, sun: 'partial', water: 'medium', evergreen: true, foliage: '#2f6a37', flower: { color: '#fdfcf2', season: 'Apr–Jun' }, climates: ['subtropical', 'mediterranean', 'temperate'], styles: ['mediterranean', 'modern', 'cottage'], spacing: 2000, price: 520, note: 'Evergreen wall cover with a wave of scented white stars.' }),
  P({ id: 'lotus', common: 'Lotus', botanical: 'Nelumbo nucifera', type: 'aquatic', form: 'aquatic', height: 900, spread: 1200, sun: 'full', water: 'high', evergreen: false, foliage: '#5f9a56', flower: { color: '#f0a8c4', season: 'Jun–Sep' }, climates: ALL.concat('temperate'), styles: ['indian', 'zen', 'tropical'], spacing: 1200, price: 900, note: 'For still ponds 300–600 mm deep; sacred and striking.' }),
  P({ id: 'water-lily', common: 'Water lily', botanical: 'Nymphaea nouchali', type: 'aquatic', form: 'aquatic', height: 200, spread: 1200, sun: 'full', water: 'high', evergreen: true, foliage: '#4f8f50', flower: { color: '#b89ae0', season: 'Year-round' }, climates: ALL, styles: ['zen', 'indian', 'tropical', 'cottage'], spacing: 1000, price: 650, note: 'Floating pads shade the water and limit algae.' }),
];

export const PLANT_BY_ID: Record<string, Plant> = Object.fromEntries(PLANTS.map((p) => [p.id, p]));

export const PLANT_TYPES: { id: PlantType; label: string }[] = [
  { id: 'tree', label: 'Trees' }, { id: 'palm', label: 'Palms' }, { id: 'shrub', label: 'Shrubs & hedges' }, { id: 'tropical', label: 'Tropical foliage' },
  { id: 'flower', label: 'Flowers' }, { id: 'grass', label: 'Grasses' }, { id: 'bamboo', label: 'Bamboo' }, { id: 'groundcover', label: 'Ground covers' },
  { id: 'succulent', label: 'Succulents' }, { id: 'climber', label: 'Climbers' }, { id: 'aquatic', label: 'Water plants' },
];

export const LANDSCAPE_STYLES: { id: LandscapeStyle; label: string; hint: string }[] = [
  { id: 'tropical', label: 'Tropical resort', hint: 'Palms, frangipani, heliconia and lush layered green' },
  { id: 'modern', label: 'Modern minimal', hint: 'Clean lawn, clipped forms, grasses and a few sculptural specimens' },
  { id: 'indian', label: 'Indian courtyard', hint: 'Shade trees, fragrant shrubs, tulsi and a kitchen garden' },
  { id: 'mediterranean', label: 'Mediterranean', hint: 'Olive, cypress, bougainvillea, lavender and gravel' },
  { id: 'zen', label: 'Zen garden', hint: 'Bamboo, maple, mondo grass, raked gravel and stone' },
  { id: 'cottage', label: 'Cottage garden', hint: 'Flowering trees, roses and deep mixed borders' },
];

/** Asset id used when a plant is placed in the model. */
export const plantAssetId = (plantId: string) => `plant-${plantId}`;

export const SUN_LABEL: Record<Sun, string> = { full: 'Full sun', partial: 'Part shade', shade: 'Shade' };
export const WATER_LABEL: Record<Water, string> = { low: 'Low water', medium: 'Moderate water', high: 'High water' };

/** Litres per plant per week at maturity — a planning figure for irrigation sizing. */
export function weeklyWater(p: Plant): number {
  const canopy = Math.PI * (p.spread / 2000) ** 2;
  return Math.round(canopy * (p.water === 'low' ? 6 : p.water === 'medium' ? 14 : 25));
}

export function searchPlants(q: string): Plant[] {
  const t = q.trim().toLowerCase();
  if (!t) return PLANTS;
  return PLANTS.filter((p) => `${p.common} ${p.botanical} ${p.type} ${p.styles.join(' ')} ${p.note}`.toLowerCase().includes(t));
}
